const fs = require('fs');
const path = require('path');

const enFile = path.join(__dirname, 'lang', 'partials', 'en', 'compare.json');
const idFile = path.join(__dirname, 'lang', 'partials', 'id', 'compare.json');

let enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));
let idData = JSON.parse(fs.readFileSync(idFile, 'utf8'));

const newEn = {
  // Custom: Spreadsheet
  "explore_spreadsheet_desc": "Stop doing manual data entry. Get a system that works for you automatically.",
  "spreadsheet_alt_title": "OneForMind vs Spreadsheets — The Ultimate Spreadsheet Alternative",
  "spreadsheet_alt_desc": "Excel and Google Sheets are blank grids that require manual labor. Switch to a ready-made Life OS.",
  "spreadsheet_alt_og_title": "Stop Doing Manual Data Entry.",
  "spreadsheet_alt_og_desc": "Why managing your life in a spreadsheet is a massive waste of time.",
  "spreadsheet_badge": "Ready-Made System",
  "spreadsheet_hero_title_1": "You Are Not",
  "spreadsheet_hero_title_2": "A Data Entry Clerk.",
  "spreadsheet_hero_desc": "Spreadsheets are powerful, but they require constant maintenance. If you forget to update a cell, the whole system breaks. <strong>OneForMind is a fully automated Life OS</strong> that does the heavy lifting for you.",
  "spreadsheet_hero_cta": "Automate Your Life",
  "spreadsheet_hero_note": "No formulas required.",
  "spreadsheet_prob_title_1": "The Maintenance",
  "spreadsheet_prob_title_highlight": "Nightmare",
  "spreadsheet_prob_desc": "When you build your own habit tracker in Excel, you spend more time fixing broken formulas than actually building the habit.",
  "spreadsheet_prob_point_1": "Zero native mobile experience",
  "spreadsheet_prob_point_2": "Requires constant manual updates",
  "spreadsheet_prob_point_3": "No built-in reminders or AI insights",
  "spreadsheet_sol_title_1": "An Opinionated",
  "spreadsheet_sol_title_highlight": "Architecture",
  "spreadsheet_sol_desc": "We made the hard design choices so you don't have to. The UI is gorgeous on every device, and your data flows seamlessly from your habits to your budget.",
  "spreadsheet_sol_1_title": "Native Mobile App Feel",
  "spreadsheet_sol_1_desc": "Works flawlessly on your phone, unlike a cramped spreadsheet.",
  "spreadsheet_sol_2_title": "Cross-Feature Intelligence",
  "spreadsheet_sol_2_desc": "Your habits talk to your planner automatically.",
  "spreadsheet_compare_title": "Manual vs Automated",
  "spreadsheet_compare_desc": "Where do you want to spend your time?",
  "spreadsheet_table_head_2": "Spreadsheets",
  "spreadsheet_table_row_1_title": "Setup Time",
  "spreadsheet_table_row_1_col_1": "Days of tweaking",
  "spreadsheet_table_row_1_col_2": "Instant",
  "spreadsheet_table_row_2_title": "Mobile UX",
  "spreadsheet_table_row_2_col_1": "Terrible",
  "spreadsheet_table_row_2_col_2": "Perfectly responsive",
  "spreadsheet_table_row_3_title": "AI Coaching",
  "spreadsheet_table_row_3_col_1": "None",
  "spreadsheet_table_row_3_col_2": "Built-in Neural Engine",
  "spreadsheet_psycho_title": "The Sunk Cost Fallacy",
  "spreadsheet_psycho_desc": "People stick with spreadsheets because they spent 20 hours building them. Don't let past effort trap you in a bad system.",
  "spreadsheet_data_title": "Action over Organization",
  "spreadsheet_data_desc": "Every minute you spend color-coding cells is a minute you aren't doing deep work.",
  "spreadsheet_cta_title": "Close the spreadsheet.<br/>Open your life.",
  "spreadsheet_cta_desc": "Switch to a system that works for you, not the other way around.",
  "spreadsheet_cta_btn": "Switch to OneForMind",

  // Custom: Notion
  "explore_notion_desc": "Cure your blank canvas syndrome. Stop designing templates and start executing.",
  "notion_alt_title": "OneForMind vs Notion — The Best Notion Alternative for Personal Use",
  "notion_alt_desc": "Notion forces you to build your own tools. OneForMind gives you a perfect, ready-made Personal OS.",
  "notion_alt_og_title": "Stop Building. Start Doing.",
  "notion_alt_og_desc": "Why Notion's blank canvas is terrible for personal productivity.",
  "notion_badge": "Opinionated OS",
  "notion_hero_title_1": "The Blank Canvas",
  "notion_hero_title_2": "Syndrome.",
  "notion_hero_desc": "Notion gives you a box of Lego bricks and tells you to build a house. <strong>OneForMind gives you the keys to a beautifully designed mansion.</strong> Stop wasting weekends designing templates and start executing your goals.",
  "notion_hero_cta": "Move In Today",
  "notion_hero_note": "Zero setup required.",
  "notion_prob_title_1": "The Endless",
  "notion_prob_title_highlight": "Tweaking",
  "notion_prob_desc": "In Notion, you are the database architect. When a database breaks or a relation fails, you have to fix it. This creates a false sense of productivity.",
  "notion_prob_point_1": "You spend hours designing instead of doing",
  "notion_prob_point_2": "Mobile app is slow and clunky",
  "notion_prob_point_3": "No native offline support",
  "notion_sol_title_1": "Structured for",
  "notion_sol_title_highlight": "Success",
  "notion_sol_desc": "OneForMind is an Opinionated OS. We baked in the best productivity frameworks (Eisenhower Matrix, Time-blocking, Atomic Habits) directly into the code. It just works.",
  "notion_sol_1_title": "Instant Onboarding",
  "notion_sol_1_desc": "No templates to download. Just sign up and go.",
  "notion_sol_2_title": "Native Speed",
  "notion_sol_2_desc": "Lightning fast interactions without the database bloat.",
  "notion_compare_title": "Builder vs User",
  "notion_compare_desc": "Do you want to build tools, or use them?",
  "notion_table_head_2": "Notion",
  "notion_table_row_1_title": "Philosophy",
  "notion_table_row_1_col_1": "Blank canvas",
  "notion_table_row_1_col_2": "Structured framework",
  "notion_table_row_2_title": "Speed",
  "notion_table_row_2_col_1": "Heavy and slow",
  "notion_table_row_2_col_2": "Instant and fluid",
  "notion_table_row_3_title": "Purpose",
  "notion_table_row_3_col_1": "Wikis and documents",
  "notion_table_row_3_col_2": "Habits, Finance, Planner",
  "notion_psycho_title": "Productivity Porn",
  "notion_psycho_desc": "Creating the 'perfect' aesthetic dashboard gives your brain cheap dopamine. But it doesn't move you closer to your life goals.",
  "notion_data_title": "Purpose-Built Engines",
  "notion_data_desc": "Notion's databases are generic. OneForMind's Habit Engine is built specifically for behavioral psychology, with heatmaps and recovery states.",
  "notion_cta_title": "Put down the Lego bricks.<br/>Pick up your life.",
  "notion_cta_desc": "Switch to a system that's already built for you.",
  "notion_cta_btn": "Get Your Ready-Made OS",

  // Custom: Obsidian
  "explore_obsidian_desc": "Obsidian is great for notes, terrible for habits. Get a real execution engine.",
  "obsidian_alt_title": "OneForMind vs Obsidian — The Obsidian Alternative for Action",
  "obsidian_alt_desc": "Obsidian is a knowledge base, not an action base. Switch to OneForMind to turn your thoughts into execution.",
  "obsidian_alt_og_title": "Notes Don't Execute Themselves.",
  "obsidian_alt_og_desc": "Why Obsidian users need a dedicated Life OS for habits and finance.",
  "obsidian_badge": "Action Engine",
  "obsidian_hero_title_1": "Knowledge is Useless",
  "obsidian_hero_title_2": "Without Action.",
  "obsidian_hero_desc": "Obsidian is fantastic for connecting thoughts. But your daily habits and financial budget shouldn't be buried in a markdown file. <strong>OneForMind is the execution layer</strong> for your life.",
  "obsidian_hero_cta": "Start Executing",
  "obsidian_hero_note": "From thinking to doing.",
  "obsidian_prob_title_1": "The Plugin",
  "obsidian_prob_title_highlight": "Rabbit Hole",
  "obsidian_prob_desc": "Trying to force Obsidian to be a habit tracker requires 15 community plugins, custom CSS, and constant maintenance. It's a fragile house of cards.",
  "obsidian_prob_point_1": "Requires complex plugin stacks",
  "obsidian_prob_point_2": "No native UI for finances or scheduling",
  "obsidian_prob_point_3": "Syncing across devices is a headache",
  "obsidian_sol_title_1": "Native",
  "obsidian_sol_title_highlight": "Integration",
  "obsidian_sol_desc": "In OneForMind, your habits, planner, and budget are native features. No plugins required. Everything syncs instantly to the cloud.",
  "obsidian_sol_1_title": "Zero Maintenance",
  "obsidian_sol_1_desc": "We handle the code. You handle your life.",
  "obsidian_sol_2_title": "Beautiful UI",
  "obsidian_sol_2_desc": "Designed to be calm and intuitive, not look like a code editor.",
  "obsidian_compare_title": "Thinking vs Doing",
  "obsidian_compare_desc": "Use the right tool for the job.",
  "obsidian_table_head_2": "Obsidian",
  "obsidian_table_row_1_title": "Primary Use",
  "obsidian_table_row_1_col_1": "Personal Knowledge",
  "obsidian_table_row_1_col_2": "Personal Execution",
  "obsidian_table_row_2_title": "Habit Tracking",
  "obsidian_table_row_2_col_1": "Hacky markdown tables",
  "obsidian_table_row_2_col_2": "Native visual engine",
  "obsidian_table_row_3_title": "Cloud Sync",
  "obsidian_table_row_3_col_1": "Paid add-on or complex",
  "obsidian_table_row_3_col_2": "Instant and included",
  "obsidian_psycho_title": "The Collector's Fallacy",
  "obsidian_psycho_desc": "We fool ourselves into thinking that collecting information is the same as taking action. Don't just log what you read; track what you DO.",
  "obsidian_data_title": "A Different Paradigm",
  "obsidian_data_desc": "Keep Obsidian for your deep research. Use OneForMind to actually execute your daily routines and manage your wealth.",
  "obsidian_cta_title": "Turn your thoughts <br/>into reality.",
  "obsidian_cta_desc": "Get the execution engine your brain deserves.",
  "obsidian_cta_btn": "Start Executing",

  // PM: Monday
  "explore_monday_desc": "You don't need a corporate project manager to run your personal habits.",
  "monday_alt_title": "OneForMind vs Monday.com — The Best Monday Alternative for Individuals",
  "monday_alt_desc": "Monday.com is built for corporations. Switch to a Personal OS designed for your individual growth.",
  "monday_alt_og_title": "You Are Not a Corporation.",
  "monday_alt_og_desc": "Why enterprise tools like Monday ruin personal productivity.",
  "monday_badge": "Personal OS",
  "monday_hero_title_1": "Leave the Office",
  "monday_hero_title_2": "At the Office.",
  "monday_hero_desc": "Monday.com is great for managing a 50-person marketing team. But using it for your personal habits and budget is overkill. <strong>OneForMind is designed specifically for individuals.</strong>",
  "monday_hero_cta": "Get Personal Clarity",
  "monday_hero_note": "No enterprise bloat.",
  "monday_prob_title_1": "Enterprise",
  "monday_prob_title_highlight": "Bloatware",
  "monday_prob_desc": "When you open Monday for your personal tasks, you are greeted with 'Workspaces', 'Boards', and 'Automations'. It's exhausting just to look at.",
  "monday_prob_point_1": "Slow and heavy interface",
  "monday_prob_point_2": "Expensive pricing model",
  "monday_prob_point_3": "No native habit or finance tracking",
  "monday_sol_title_1": "Designed for",
  "monday_sol_title_highlight": "Humans",
  "monday_sol_desc": "OneForMind is a sanctuary. We stripped away all the corporate features and left only what you need to master your own mind and life.",
  "monday_sol_1_title": "Calm Interface",
  "monday_sol_1_desc": "No stressful charts or team notifications.",
  "monday_sol_2_title": "Holistic Tracking",
  "monday_sol_2_desc": "Track your wealth, not your sprint velocity.",
  "monday_compare_title": "Corporate vs Personal",
  "monday_compare_desc": "Where do you belong?",
  "monday_table_head_2": "Monday.com",
  "monday_table_row_1_title": "Target Audience",
  "monday_table_row_1_col_1": "Corporate Teams",
  "monday_table_row_1_col_2": "Ambitious Individuals",
  "monday_table_row_2_title": "Complexity",
  "monday_table_row_2_col_1": "Overwhelming",
  "monday_table_row_2_col_2": "Streamlined",
  "monday_table_row_3_title": "Price",
  "monday_table_row_3_col_1": "Per-user enterprise pricing",
  "monday_table_row_3_col_2": "Fair individual pricing",
  "monday_psycho_title": "Context Bleed",
  "monday_psycho_desc": "Using the same tool for work and personal life prevents your brain from ever 'clocking out'. Give your personal life its own dedicated space.",
  "monday_data_title": "Deep Personal Context",
  "monday_data_desc": "Monday tracks deadlines. OneForMind tracks your mood, your finances, and your daily habits to give you real life insights.",
  "monday_cta_title": "Fire your corporate <br/>software.",
  "monday_cta_desc": "Reclaim your personal life with a dedicated OS.",
  "monday_cta_btn": "Switch to a Personal OS",

  // PM: Trello
  "explore_trello_desc": "Moving cards across a board doesn't build discipline. Get a real execution system.",
  "trello_alt_title": "OneForMind vs Trello — The Superior Trello Alternative",
  "trello_alt_desc": "Kanban boards are for software development, not personal life. Switch to OneForMind.",
  "trello_alt_og_title": "Kanban Boards Aren't Enough.",
  "trello_alt_og_desc": "Why dragging cards in Trello fails to build lasting personal habits.",
  "trello_badge": "Beyond Kanban",
  "trello_hero_title_1": "Life Doesn't Fit",
  "trello_hero_title_2": "On a Kanban Board.",
  "trello_hero_desc": "Trello's 'To Do, Doing, Done' columns are great for software bugs. But personal growth requires nuance. <strong>OneForMind offers Time-Blocking and Habit Heatmaps</strong>, giving you the right tool for the right job.",
  "trello_hero_cta": "Upgrade Your System",
  "trello_hero_note": "Stop dragging cards.",
  "trello_prob_title_1": "The Illusion of",
  "trello_prob_title_highlight": "Progress",
  "trello_prob_desc": "Dragging a card from 'To Do' to 'Done' feels good, but it lacks scheduling context. A task without a scheduled time is just a wish.",
  "trello_prob_point_1": "No native calendar view",
  "trello_prob_point_2": "Terrible for tracking daily habits",
  "trello_prob_point_3": "Lists get infinitely long and messy",
  "trello_sol_title_1": "Time-Blocking",
  "trello_sol_title_highlight": "Supremacy",
  "trello_sol_desc": "OneForMind forces you to put tasks onto a timeline. If it's not blocked on your calendar, it won't get done. This forces ruthless prioritization.",
  "trello_sol_1_title": "Eisenhower Matrix",
  "trello_sol_1_desc": "Prioritize before you schedule.",
  "trello_sol_2_title": "Dedicated Habit Engine",
  "trello_sol_2_desc": "Separate your routines from your one-off tasks.",
  "trello_compare_title": "Dragging vs Executing",
  "trello_compare_desc": "How do you get things done?",
  "trello_table_head_2": "Trello",
  "trello_table_row_1_title": "Methodology",
  "trello_table_row_1_col_1": "Kanban Boards",
  "trello_table_row_1_col_2": "Time-Blocking & Matrix",
  "trello_table_row_2_title": "Habit Tracking",
  "trello_table_row_2_col_1": "Clunky checklists",
  "trello_table_row_2_col_2": "Native visual engine",
  "trello_table_row_3_title": "Finance Integration",
  "trello_table_row_3_col_1": "None",
  "trello_table_row_3_col_2": "Deeply integrated",
  "trello_psycho_title": "Parkinson's Law",
  "trello_psycho_desc": "Work expands to fill the time allotted. Trello cards have no time limits. OneForMind's time-blocks force you to finish within a set boundary.",
  "trello_data_title": "Visualizing Time",
  "trello_data_desc": "You can't manage what you can't see. Seeing your day as a series of blocks gives you an honest assessment of your capacity.",
  "trello_cta_title": "Stop moving cards. <br/>Start moving forward.",
  "trello_cta_desc": "Switch to a system that respects your time.",
  "trello_cta_btn": "Start Time-Blocking",

  // PM: Asana
  "explore_asana_desc": "Enterprise tools kill personal productivity. Get an OS that feels like a sanctuary.",
  "asana_alt_title": "OneForMind vs Asana — The Asana Alternative for Individuals",
  "asana_alt_desc": "Asana is for managing employees. OneForMind is for managing yourself. Switch to a true Personal OS.",
  "asana_alt_og_title": "You Are Not a Project Manager.",
  "asana_alt_og_desc": "Why using Asana for your personal life is a massive mistake.",
  "asana_badge": "Individual Focus",
  "asana_hero_title_1": "You Don't Need",
  "asana_hero_title_2": "A Project Manager.",
  "asana_hero_desc": "Asana is built to track employee deadlines. Using it for your personal goals feels cold and sterile. <strong>OneForMind is a personal sanctuary</strong> designed to help you grow, not just meet a KPI.",
  "asana_hero_cta": "Reclaim Your Focus",
  "asana_hero_note": "No status meetings required.",
  "asana_prob_title_1": "The Corporate",
  "asana_prob_title_highlight": "Coldness",
  "asana_prob_desc": "There is no joy in checking off a personal milestone in a tool designed for corporate surveillance. The UI is cluttered with features you will never use.",
  "asana_prob_point_1": "Sterile, work-focused interface",
  "asana_prob_point_2": "Too complex for simple daily habits",
  "asana_prob_point_3": "No space for personal reflection",
  "asana_sol_title_1": "A Digital",
  "asana_sol_title_highlight": "Sanctuary",
  "asana_sol_desc": "We built OneForMind to be beautiful. It includes a mindfulness journal, a visual finance vault, and a calm daily planner. It's a place you actually want to visit.",
  "asana_sol_1_title": "Integrated Journal",
  "asana_sol_1_desc": "Reflect on your progress, don't just report it.",
  "asana_sol_2_title": "Personal Wealth",
  "asana_sol_2_desc": "Track your savings goals natively.",
  "asana_compare_title": "Reporting vs Reflecting",
  "asana_compare_desc": "Who are you working for?",
  "asana_table_head_2": "Asana",
  "asana_table_row_1_title": "Vibe",
  "asana_table_row_1_col_1": "Corporate reporting",
  "asana_table_row_1_col_2": "Personal sanctuary",
  "asana_table_row_2_title": "Features",
  "asana_table_row_2_col_1": "Team collaboration",
  "asana_table_row_2_col_2": "Habits, Finance, Journal",
  "asana_table_row_3_title": "Setup",
  "asana_table_row_3_col_1": "Complex projects",
  "asana_table_row_3_col_2": "Simple daily flow",
  "asana_psycho_title": "The Environment Effect",
  "asana_psycho_desc": "The digital environment you use shapes your mindset. A corporate tool puts you in a stressed, reporting mindset. A personal OS puts you in a growth mindset.",
  "asana_data_title": "Whole-Life Metrics",
  "asana_data_desc": "Asana measures tasks completed. OneForMind measures your financial health, habit consistency, and emotional well-being.",
  "asana_cta_title": "Clock out of <br/>corporate software.",
  "asana_cta_desc": "Step into a beautiful Personal OS.",
  "asana_cta_btn": "Step Into OneForMind"
};

const newId = {
  // Custom: Spreadsheet
  "explore_spreadsheet_desc": "Berhenti masukin data manual. Dapatkan sistem yang otomatis kerja buatmu.",
  "spreadsheet_alt_title": "OneForMind vs Spreadsheet — Alternatif Spreadsheet Terbaik",
  "spreadsheet_alt_desc": "Excel dan Google Sheets itu kosong dan butuh kerja kasar. Beralih ke Life OS siap pakai.",
  "spreadsheet_alt_og_title": "Berhenti Entri Data Manual.",
  "spreadsheet_alt_og_desc": "Kenapa ngatur hidup pakai spreadsheet itu buang-buang waktu banget.",
  "spreadsheet_badge": "Sistem Siap Pakai",
  "spreadsheet_hero_title_1": "Kamu Itu Bukan",
  "spreadsheet_hero_title_2": "Tukang Entri Data.",
  "spreadsheet_hero_desc": "Spreadsheet emang canggih, tapi butuh dirawat terus. Lupa update satu sel aja, sistemnya hancur. <strong>OneForMind adalah Life OS otomatis</strong> yang ngelakuin kerja berat buatmu.",
  "spreadsheet_hero_cta": "Otomatiskan Hidupmu",
  "spreadsheet_hero_note": "Nggak butuh rumus Excel.",
  "spreadsheet_prob_title_1": "Mimpi Buruk",
  "spreadsheet_prob_title_highlight": "Pemeliharaan",
  "spreadsheet_prob_desc": "Pas kamu bikin habit tracker di Excel, kamu lebih banyak ngabisin waktu benerin rumus error daripada beneran ngebangun habitnya.",
  "spreadsheet_prob_point_1": "Pengalaman di HP jelek banget",
  "spreadsheet_prob_point_2": "Butuh update manual terus-terusan",
  "spreadsheet_prob_point_3": "Nggak ada pengingat bawaan atau insight AI",
  "spreadsheet_sol_title_1": "Arsitektur yang",
  "spreadsheet_sol_title_highlight": "Berprinsip",
  "spreadsheet_sol_desc": "Kami udah ngambil keputusan desain tersulit biar kamu nggak pusing. UI-nya cakep di semua layar, dan datamu ngalir mulus dari habit ke anggaran.",
  "spreadsheet_sol_1_title": "Terasa Kayak App Native",
  "spreadsheet_sol_1_desc": "Lancar jaya di HP, nggak kayak spreadsheet yang sempit.",
  "spreadsheet_sol_2_title": "Kecerdasan Lintas Fitur",
  "spreadsheet_sol_2_desc": "Habitmu ngobrol langsung sama planner secara otomatis.",
  "spreadsheet_compare_title": "Manual vs Otomatis",
  "spreadsheet_compare_desc": "Kamu mau ngabisin waktu buat apa?",
  "spreadsheet_table_head_2": "Spreadsheet",
  "spreadsheet_table_row_1_title": "Waktu Setup",
  "spreadsheet_table_row_1_col_1": "Berhari-hari ngatur rumus",
  "spreadsheet_table_row_1_col_2": "Instan",
  "spreadsheet_table_row_2_title": "UX di HP",
  "spreadsheet_table_row_2_col_1": "Mengerikan",
  "spreadsheet_table_row_2_col_2": "Responsif sempurna",
  "spreadsheet_table_row_3_title": "Pelatih AI",
  "spreadsheet_table_row_3_col_1": "Nggak ada",
  "spreadsheet_table_row_3_col_2": "Mesin Neural Bawaan",
  "spreadsheet_psycho_title": "Sunk Cost Fallacy",
  "spreadsheet_psycho_desc": "Orang bertahan pakai spreadsheet karena udah buang 20 jam bikinnya. Jangan biarkan usaha masa lalu menjebakmu di sistem yang buruk.",
  "spreadsheet_data_title": "Tindakan di Atas Organisasi",
  "spreadsheet_data_desc": "Tiap menit yang kamu pakai buat ngewarnain sel Excel adalah menit yang hilang buat kerja sungguhan.",
  "spreadsheet_cta_title": "Tutup spreadsheet-nya.<br/>Buka hidupmu.",
  "spreadsheet_cta_desc": "Beralih ke sistem yang kerja buatmu, bukan sebaliknya.",
  "spreadsheet_cta_btn": "Beralih ke OneForMind",

  // Custom: Notion
  "explore_notion_desc": "Sembuhkan sindrom kanvas kosongmu. Berhenti ngedesain template, mulai eksekusi.",
  "notion_alt_title": "OneForMind vs Notion — Alternatif Notion Terbaik buat Pribadi",
  "notion_alt_desc": "Notion maksa kamu bikin alat sendiri. OneForMind ngasih Personal OS yang udah jadi dan sempurna.",
  "notion_alt_og_title": "Berhenti Bikin Template. Mulai Kerja.",
  "notion_alt_og_desc": "Kenapa kanvas kosong Notion itu buruk banget buat produktivitas pribadi.",
  "notion_badge": "Opinionated OS",
  "notion_hero_title_1": "Sindrom",
  "notion_hero_title_2": "Kanvas Kosong.",
  "notion_hero_desc": "Notion ngasih kamu sekotak Lego dan nyuruh kamu bikin rumah. <strong>OneForMind ngasih kamu kunci ke mansion yang udah didesain indah.</strong> Berhenti buang waktu akhir pekan buat ngedesain template dan mulailah mengeksekusi targetmu.",
  "notion_hero_cta": "Pindah Sekarang",
  "notion_hero_note": "Nggak butuh setup sama sekali.",
  "notion_prob_title_1": "Ngulik Terus",
  "notion_prob_title_highlight": "Tanpa Henti",
  "notion_prob_desc": "Di Notion, kamu itu arsitek database. Kalau ada relasi database yang rusak, kamu yang harus benerin. Ini nyiptain ilusi seolah-olah kamu lagi produktif.",
  "notion_prob_point_1": "Habis waktu buat ngedesain, bukan ngerjain",
  "notion_prob_point_2": "Aplikasi HP-nya lambat dan kaku",
  "notion_prob_point_3": "Nggak ada support offline bawaan",
  "notion_sol_title_1": "Terstruktur buat",
  "notion_sol_title_highlight": "Sukses",
  "notion_sol_desc": "OneForMind itu Opinionated OS. Kami udah masukin kerangka produktivitas terbaik (Matriks Eisenhower, Time-blocking, Atomic Habits) langsung ke dalam kodenya. Tinggal pakai.",
  "notion_sol_1_title": "Onboarding Instan",
  "notion_sol_1_desc": "Nggak usah download template. Daftar dan langsung jalan.",
  "notion_sol_2_title": "Kecepatan Native",
  "notion_sol_2_desc": "Interaksi secepat kilat tanpa beban database yang berat.",
  "notion_compare_title": "Pembuat vs Pengguna",
  "notion_compare_desc": "Kamu mau bikin alat, atau makai alat?",
  "notion_table_head_2": "Notion",
  "notion_table_row_1_title": "Filosofi",
  "notion_table_row_1_col_1": "Kanvas kosong",
  "notion_table_row_1_col_2": "Kerangka terstruktur",
  "notion_table_row_2_title": "Kecepatan",
  "notion_table_row_2_col_1": "Berat dan lambat",
  "notion_table_row_2_col_2": "Instan dan mulus",
  "notion_table_row_3_title": "Tujuan",
  "notion_table_row_3_col_1": "Wiki dan dokumen",
  "notion_table_row_3_col_2": "Habit, Keuangan, Planner",
  "notion_psycho_title": "Pornografi Produktivitas",
  "notion_psycho_desc": "Bikin dashboard aesthetic yang 'sempurna' ngasih otakmu dopamin murahan. Tapi itu nggak bawa kamu lebih deket ke tujuan hidupmu.",
  "notion_data_title": "Mesin Khusus",
  "notion_data_desc": "Database Notion itu generik. Mesin Habit OneForMind dibangun khusus buat psikologi perilaku, lengkap dengan heatmap dan pemulihan.",
  "notion_cta_title": "Taruh mainan Legonya.<br/>Fokus ke hidupmu.",
  "notion_cta_desc": "Beralih ke sistem yang udah dibangun khusus buatmu.",
  "notion_cta_btn": "Dapatkan OS Siap Pakai",

  // Custom: Obsidian
  "explore_obsidian_desc": "Obsidian itu keren buat catatan, tapi buruk buat habit. Dapatkan mesin eksekusi nyata.",
  "obsidian_alt_title": "OneForMind vs Obsidian — Alternatif Obsidian untuk Eksekusi",
  "obsidian_alt_desc": "Obsidian adalah basis pengetahuan, bukan basis tindakan. Beralih ke OneForMind buat ngubah pikiran jadi tindakan.",
  "obsidian_alt_og_title": "Catatan Nggak Bisa Eksekusi Sendiri.",
  "obsidian_alt_og_desc": "Kenapa pengguna Obsidian butuh Life OS khusus buat habit dan keuangan.",
  "obsidian_badge": "Mesin Eksekusi",
  "obsidian_hero_title_1": "Pengetahuan Itu Percuma",
  "obsidian_hero_title_2": "Tanpa Tindakan.",
  "obsidian_hero_desc": "Obsidian itu luar biasa buat ngehubungin pikiran. Tapi habit harian dan anggaran keuanganmu nggak seharusnya dikubur di dalem file markdown. <strong>OneForMind adalah lapisan eksekusi</strong> buat hidupmu.",
  "obsidian_hero_cta": "Mulai Eksekusi",
  "obsidian_hero_note": "Dari berpikir jadi bertindak.",
  "obsidian_prob_title_1": "Lubang Hitam",
  "obsidian_prob_title_highlight": "Plugin",
  "obsidian_prob_desc": "Maksa Obsidian jadi habit tracker itu butuh 15 plugin komunitas, CSS kustom, dan perbaikan terus-menerus. Itu sistem yang sangat rapuh.",
  "obsidian_prob_point_1": "Butuh tumpukan plugin yang rumit",
  "obsidian_prob_point_2": "Nggak ada UI bawaan buat uang atau jadwal",
  "obsidian_prob_point_3": "Sinkronisasi antar HP itu bikin pusing",
  "obsidian_sol_title_1": "Integrasi",
  "obsidian_sol_title_highlight": "Bawaan",
  "obsidian_sol_desc": "Di OneForMind, habit, planner, dan anggaranmu itu fitur bawaan. Nggak butuh plugin. Semuanya sinkron instan ke cloud.",
  "obsidian_sol_1_title": "Nol Pemeliharaan",
  "obsidian_sol_1_desc": "Kami yang ngurus kodenya. Kamu urus hidupmu.",
  "obsidian_sol_2_title": "UI yang Indah",
  "obsidian_sol_2_desc": "Didesain biar tenang dan intuitif, bukan keliatan kayak code editor.",
  "obsidian_compare_title": "Berpikir vs Bertindak",
  "obsidian_compare_desc": "Pakai alat yang bener buat tugasnya.",
  "obsidian_table_head_2": "Obsidian",
  "obsidian_table_row_1_title": "Fungsi Utama",
  "obsidian_table_row_1_col_1": "Pengetahuan Pribadi",
  "obsidian_table_row_1_col_2": "Eksekusi Pribadi",
  "obsidian_table_row_2_title": "Pelacakan Habit",
  "obsidian_table_row_2_col_1": "Tabel markdown yang dipaksain",
  "obsidian_table_row_2_col_2": "Mesin visual bawaan",
  "obsidian_table_row_3_title": "Cloud Sync",
  "obsidian_table_row_3_col_1": "Bayar tambahan atau rumit",
  "obsidian_table_row_3_col_2": "Instan dan udah termasuk",
  "obsidian_psycho_title": "Kesesatan Kolektor",
  "obsidian_psycho_desc": "Kita nipu diri sendiri dengan mikir kalau ngumpulin informasi itu sama dengan ngambil tindakan. Jangan cuma nyatet apa yang kamu baca; lacak apa yang kamu LAKUKAN.",
  "obsidian_data_title": "Paradigma yang Beda",
  "obsidian_data_desc": "Simpan Obsidian buat riset mendalammu. Pakai OneForMind buat beneran mengeksekusi rutinitas harian dan ngatur kekayaanmu.",
  "obsidian_cta_title": "Ubah pikiranmu <br/>jadi realita.",
  "obsidian_cta_desc": "Dapatkan mesin eksekusi yang pantas buat otakmu.",
  "obsidian_cta_btn": "Mulai Eksekusi",

  // PM: Monday
  "explore_monday_desc": "Kamu nggak butuh manajer proyek perusahaan buat jalanin habit pribadimu.",
  "monday_alt_title": "OneForMind vs Monday.com — Alternatif Monday Terbaik buat Pribadi",
  "monday_alt_desc": "Monday.com dibuat buat korporasi. Beralih ke Personal OS yang didesain buat pertumbuhan individumu.",
  "monday_alt_og_title": "Kamu Itu Bukan Korporasi.",
  "monday_alt_og_desc": "Kenapa alat perusahaan kayak Monday ngerusak produktivitas pribadi.",
  "monday_badge": "Personal OS",
  "monday_hero_title_1": "Tinggalkan Kerjaan",
  "monday_hero_title_2": "Di Kantor.",
  "monday_hero_desc": "Monday.com bagus buat ngatur 50 orang tim marketing. Tapi pakai itu buat habit dan anggaran pribadi itu lebay banget. <strong>OneForMind didesain khusus buat individu.</strong>",
  "monday_hero_cta": "Dapatkan Kejelasan",
  "monday_hero_note": "Tanpa keribetan perusahaan.",
  "monday_prob_title_1": "Aplikasi",
  "monday_prob_title_highlight": "Korporat",
  "monday_prob_desc": "Pas kamu buka Monday buat tugas pribadi, kamu disambut sama 'Workspaces', 'Boards', dan 'Automations'. Ngeliatnya aja udah capek.",
  "monday_prob_point_1": "Antarmuka yang lambat dan berat",
  "monday_prob_point_2": "Model harga yang mahal",
  "monday_prob_point_3": "Nggak ada pelacakan habit atau uang",
  "monday_sol_title_1": "Didesain buat",
  "monday_sol_title_highlight": "Manusia",
  "monday_sol_desc": "OneForMind itu tempat yang tenang. Kami ngebuang semua fitur korporat dan cuma nyisain apa yang kamu butuhin buat nguasain pikiran dan hidupmu.",
  "monday_sol_1_title": "Antarmuka Tenang",
  "monday_sol_1_desc": "Nggak ada grafik bikin stres atau notif tim.",
  "monday_sol_2_title": "Pelacakan Holistik",
  "monday_sol_2_desc": "Lacak kekayaanmu, bukan sprint velocity-mu.",
  "monday_compare_title": "Korporat vs Personal",
  "monday_compare_desc": "Di mana tempatmu sebenarnya?",
  "monday_table_head_2": "Monday.com",
  "monday_table_row_1_title": "Target Audiens",
  "monday_table_row_1_col_1": "Tim Perusahaan",
  "monday_table_row_1_col_2": "Individu Ambisius",
  "monday_table_row_2_title": "Kerumitan",
  "monday_table_row_2_col_1": "Bikin pusing",
  "monday_table_row_2_col_2": "Sangat rapi",
  "monday_table_row_3_title": "Harga",
  "monday_table_row_3_col_1": "Harga enterprise per-user",
  "monday_table_row_3_col_2": "Harga wajar buat individu",
  "monday_psycho_title": "Bocornya Konteks",
  "monday_psycho_desc": "Pakai aplikasi yang sama buat kerja dan kehidupan pribadi bikin otakmu nggak pernah bener-bener 'pulang kantor'. Kasih kehidupan pribadimu ruang khususnya sendiri.",
  "monday_data_title": "Konteks Personal Mendalam",
  "monday_data_desc": "Monday ngelacak deadline. OneForMind ngelacak moodmu, keuanganmu, dan habit harianmu buat ngasih insight hidup yang nyata.",
  "monday_cta_title": "Pecat software <br/>kantoranmu.",
  "monday_cta_desc": "Rebut kembali kehidupan pribadimu dengan OS khusus.",
  "monday_cta_btn": "Beralih ke Personal OS",

  // PM: Trello
  "explore_trello_desc": "Geser-geser kartu di papan nggak bikin kamu disiplin. Dapatkan sistem eksekusi nyata.",
  "trello_alt_title": "OneForMind vs Trello — Alternatif Trello Superior",
  "trello_alt_desc": "Papan Kanban itu buat ngembangin software, bukan hidup. Beralih ke OneForMind.",
  "trello_alt_og_title": "Papan Kanban Aja Nggak Cukup.",
  "trello_alt_og_desc": "Kenapa geser kartu di Trello gagal ngebangun habit yang bertahan lama.",
  "trello_badge": "Lebih dari Kanban",
  "trello_hero_title_1": "Hidup Itu Nggak Muat",
  "trello_hero_title_2": "Di Papan Kanban.",
  "trello_hero_desc": "Kolom 'To Do, Doing, Done' Trello itu bagus buat bug software. Tapi pertumbuhan pribadi butuh kehalusan. <strong>OneForMind ngasih Time-Blocking dan Heatmap Habit</strong>, alat yang bener buat tugas yang bener.",
  "trello_hero_cta": "Upgrade Sistemmu",
  "trello_hero_note": "Berhenti ngegeser kartu.",
  "trello_prob_title_1": "Ilusi",
  "trello_prob_title_highlight": "Kemajuan",
  "trello_prob_desc": "Ngegeser kartu dari 'To Do' ke 'Done' kerasa enak, tapi nggak ada konteks jadwal. Tugas tanpa jadwal waktu itu cuma angan-angan.",
  "trello_prob_point_1": "Nggak ada tampilan kalender bawaan",
  "trello_prob_point_2": "Buruk banget buat ngelacak habit harian",
  "trello_prob_point_3": "Daftar jadi panjang banget dan berantakan",
  "trello_sol_title_1": "Kehebatan",
  "trello_sol_title_highlight": "Time-Blocking",
  "trello_sol_desc": "OneForMind maksa kamu masukin tugas ke timeline. Kalau nggak di-block di kalendermu, itu nggak bakal dikerjain. Ini maksa penentuan prioritas yang kejam.",
  "trello_sol_1_title": "Matriks Eisenhower",
  "trello_sol_1_desc": "Prioritaskan sebelum menjadwalkan.",
  "trello_sol_2_title": "Mesin Habit Khusus",
  "trello_sol_2_desc": "Pisahkan rutinitas dari tugas sekali jalan.",
  "trello_compare_title": "Ngegeser vs Mengeksekusi",
  "trello_compare_desc": "Gimana kamu nyelesein sesuatu?",
  "trello_table_head_2": "Trello",
  "trello_table_row_1_title": "Metodologi",
  "trello_table_row_1_col_1": "Papan Kanban",
  "trello_table_row_1_col_2": "Time-Blocking & Matriks",
  "trello_table_row_2_title": "Pelacakan Habit",
  "trello_table_row_2_col_1": "Checklist yang kaku",
  "trello_table_row_2_col_2": "Mesin visual bawaan",
  "trello_table_row_3_title": "Integrasi Keuangan",
  "trello_table_row_3_col_1": "Nggak ada",
  "trello_table_row_3_col_2": "Terintegrasi mendalam",
  "trello_psycho_title": "Hukum Parkinson",
  "trello_psycho_desc": "Kerjaan bakal melebar ngisi waktu yang ada. Kartu Trello nggak punya batas waktu. Time-block OneForMind maksa kamu nyelesein kerjaan dalam batas waktu yang jelas.",
  "trello_data_title": "Memvisualisasikan Waktu",
  "trello_data_desc": "Kamu nggak bisa ngatur apa yang nggak bisa kamu liat. Ngeliat harimu sebagai serangkaian blok ngasih penilaian jujur soal kapasitasmu.",
  "trello_cta_title": "Berhenti ngegeser kartu. <br/>Mulai bergerak maju.",
  "trello_cta_desc": "Beralih ke sistem yang ngehargain waktumu.",
  "trello_cta_btn": "Mulai Time-Blocking",

  // PM: Asana
  "explore_asana_desc": "Alat perusahaan ngebunuh produktivitas pribadi. Dapatkan OS yang kerasa kayak tempat berlindung.",
  "asana_alt_title": "OneForMind vs Asana — Alternatif Asana buat Individu",
  "asana_alt_desc": "Asana itu buat ngatur karyawan. OneForMind itu buat ngatur diri sendiri. Beralih ke Personal OS sejati.",
  "asana_alt_og_title": "Kamu Itu Bukan Manajer Proyek.",
  "asana_alt_og_desc": "Kenapa pakai Asana buat kehidupan pribadi itu kesalahan besar.",
  "asana_badge": "Fokus Individu",
  "asana_hero_title_1": "Kamu Nggak Butuh",
  "asana_hero_title_2": "Manajer Proyek.",
  "asana_hero_desc": "Asana dibikin buat ngelacak deadline karyawan. Pakai itu buat tujuan pribadi kerasa dingin dan kaku. <strong>OneForMind adalah ruang suci pribadi</strong> yang didesain buat ngebantu kamu tumbuh, bukan cuma menuhi KPI.",
  "asana_hero_cta": "Rebut Kembali Fokusmu",
  "asana_hero_note": "Nggak butuh meeting status.",
  "asana_prob_title_1": "Kedinginan",
  "asana_prob_title_highlight": "Korporat",
  "asana_prob_desc": "Nggak ada seneng-senengnya nyentang pencapaian pribadi di alat yang didesain buat pengawasan perusahaan. UI-nya penuh sama fitur yang nggak bakal pernah kamu pakai.",
  "asana_prob_point_1": "Kaku, antarmuka fokus kerjaan",
  "asana_prob_point_2": "Terlalu rumit buat habit harian simpel",
  "asana_prob_point_3": "Nggak ada ruang buat refleksi pribadi",
  "asana_sol_title_1": "Ruang Suci",
  "asana_sol_title_highlight": "Digital",
  "asana_sol_desc": "Kami ngebangun OneForMind biar cantik. Udah termasuk jurnal mindfulness, brankas keuangan visual, dan planner harian yang tenang. Ini tempat yang beneran pengen kamu kunjungin.",
  "asana_sol_1_title": "Jurnal Terintegrasi",
  "asana_sol_1_desc": "Refleksikan progresmu, jangan cuma dilaporin.",
  "asana_sol_2_title": "Kekayaan Pribadi",
  "asana_sol_2_desc": "Lacak tujuan tabunganmu secara langsung.",
  "asana_compare_title": "Laporan vs Refleksi",
  "asana_compare_desc": "Kamu kerja buat siapa?",
  "asana_table_head_2": "Asana",
  "asana_table_row_1_title": "Suasana (Vibe)",
  "asana_table_row_1_col_1": "Laporan perusahaan",
  "asana_table_row_1_col_2": "Ruang suci pribadi",
  "asana_table_row_2_title": "Fitur",
  "asana_table_row_2_col_1": "Kolaborasi tim",
  "asana_table_row_2_col_2": "Habit, Keuangan, Jurnal",
  "asana_table_row_3_title": "Setup",
  "asana_table_row_3_col_1": "Proyek yang rumit",
  "asana_table_row_3_col_2": "Alur harian simpel",
  "asana_psycho_title": "Efek Lingkungan",
  "asana_psycho_desc": "Lingkungan digital yang kamu pakai ngebentuk mindsetmu. Alat korporat bikin kamu stres dan bermental laporan. Personal OS bikin kamu bermental pertumbuhan.",
  "asana_data_title": "Metrik Kehidupan Penuh",
  "asana_data_desc": "Asana ngukur tugas yang selesai. OneForMind ngukur kesehatan keuangan, konsistensi habit, dan kesejahteraan emosionalmu.",
  "asana_cta_title": "Clock out dari <br/>software korporat.",
  "asana_cta_desc": "Masuklah ke Personal OS yang indah.",
  "asana_cta_btn": "Masuk ke OneForMind"
};

Object.assign(enData, newEn);
Object.assign(idData, newId);

fs.writeFileSync(enFile, JSON.stringify(enData, null, 2), 'utf8');
fs.writeFileSync(idFile, JSON.stringify(idData, null, 2), 'utf8');
console.log('Language files updated successfully.');
