const fs = require('fs');
const path = require('path');

const enFile = path.join(__dirname, 'lang', 'partials', 'en', 'compare.json');
const idFile = path.join(__dirname, 'lang', 'partials', 'id', 'compare.json');

let enData = JSON.parse(fs.readFileSync(enFile, 'utf8'));
let idData = JSON.parse(fs.readFileSync(idFile, 'utf8'));

// Data to add for English
const newEn = {
  // Finance: YNAB
  "explore_ynab_desc": "Stop needing an accounting degree just to track your coffee. Get visual, habit-driven finances.",
  "ynab_alt_title": "OneForMind vs YNAB — The Best YNAB Alternative",
  "ynab_alt_desc": "YNAB is too complex and expensive. Switch to a visual Finance OS that connects your spending to your daily habits.",
  "ynab_alt_og_title": "You Don't Need an Accounting Degree to Budget.",
  "ynab_alt_og_desc": "Why pay $109/year for a glorified spreadsheet when you can have a unified Life OS?",
  "ynab_badge": "Visual Finance OS",
  "ynab_hero_title_1": "You Need A Life,",
  "ynab_hero_title_2": "Not Just A Budget.",
  "ynab_hero_desc": "YNAB forces you to become a part-time accountant. OneForMind gives you a <strong>beautiful, intuitive dashboard</strong> that tracks your money while connecting it to your real-world habits. Stop balancing spreadsheets and start living.",
  "ynab_hero_cta": "Try Visual Budgeting",
  "ynab_hero_note": "No accounting degree required.",
  "ynab_prob_title_1": "The Complexity",
  "ynab_prob_title_highlight": "Trap",
  "ynab_prob_desc": "When budgeting feels like doing your taxes, you'll eventually stop doing it. YNAB's steep learning curve makes financial awareness a chore rather than a habit.",
  "ynab_prob_point_1": "Extremely steep learning curve",
  "ynab_prob_point_2": "Punishing $109/year subscription fee",
  "ynab_prob_point_3": "It's just a spreadsheet with lipstick",
  "ynab_sol_title_1": "Clarity Over",
  "ynab_sol_title_highlight": "Complexity",
  "ynab_sol_desc": "We believe managing your money should take 2 minutes a day. Our visual vaults, colorful transaction tags, and simple budget bars give you instant clarity without the headache.",
  "ynab_sol_1_title": "Habit-Driven Finance",
  "ynab_sol_1_desc": "See exactly how your 'Eat Out Less' habit correlates with your bank account.",
  "ynab_sol_2_title": "Visual Savings Vaults",
  "ynab_sol_2_desc": "Watch your money grow towards your dreams, not just sit in categories.",
  "ynab_compare_title": "Spreadsheets vs Visual OS",
  "ynab_compare_desc": "Which one do you actually want to open?",
  "ynab_table_head_2": "YNAB",
  "ynab_table_row_1_title": "Learning Curve",
  "ynab_table_row_1_col_1": "Requires hours of tutorials",
  "ynab_table_row_1_col_2": "Intuitive from minute one",
  "ynab_table_row_2_title": "Habit Integration",
  "ynab_table_row_2_col_1": "None",
  "ynab_table_row_2_col_2": "Deeply integrated",
  "ynab_table_row_3_title": "Price",
  "ynab_table_row_3_col_1": "$109/year",
  "ynab_table_row_3_col_2": "Much more affordable",
  "ynab_cost_title": "The Absurdity of Paying $109 to Save Money",
  "ynab_cost_desc": "It's ironic: an app designed to help you save money is one of your biggest software expenses. With OneForMind, you get a full Life OS for less.",
  "ynab_psycho_title": "Financial Fatigue",
  "ynab_psycho_desc": "When every penny must be 'given a job', the mental load is exhausting. We use macro-budgets and visual cues to keep you aware without the burnout.",
  "ynab_cta_title": "Ready to fire your <br/>robot accountant?",
  "ynab_cta_desc": "Switch to a system that actually makes sense.",
  "ynab_cta_btn": "Switch to OneForMind",

  // Finance: Wallet
  "explore_wallet_desc": "Passive automation is a trap. Stop letting apps do the work while your wallet bleeds.",
  "wallet_alt_title": "OneForMind vs Wallet App — A Better Wallet Alternative",
  "wallet_alt_desc": "Wallet's passive bank syncing makes you lazy. Take active control of your finances with OneForMind.",
  "wallet_alt_og_title": "Automation is Making You Broke.",
  "wallet_alt_og_desc": "Why passive tracking apps like Wallet fail to change your spending habits.",
  "wallet_badge": "Active Financial Awareness",
  "wallet_hero_title_1": "Stop Watching Your",
  "wallet_hero_title_2": "Money Disappear.",
  "wallet_hero_desc": "Apps like Wallet brag about automatic bank syncing. But when the app does all the work, your brain goes on autopilot. <strong>You need active awareness</strong>, not a post-mortem report of your empty bank account.",
  "wallet_hero_cta": "Take Active Control",
  "wallet_hero_note": "Feel every transaction.",
  "wallet_prob_title_1": "The Automation",
  "wallet_prob_title_highlight": "Illusion",
  "wallet_prob_desc": "Syncing your bank feels productive, but it's totally passive. You only open the app at the end of the month to see the damage that's already done.",
  "wallet_prob_point_1": "You don't 'feel' your spending",
  "wallet_prob_point_2": "Delayed realization of over-budgeting",
  "wallet_prob_point_3": "Creates financial detachment",
  "wallet_sol_title_1": "Friction is a",
  "wallet_sol_title_highlight": "Feature",
  "wallet_sol_desc": "OneForMind requires manual entry by design. Taking 5 seconds to type in your $6 coffee forces you to acknowledge the purchase. That tiny friction is what actually changes your spending behavior.",
  "wallet_sol_1_title": "Active Logging",
  "wallet_sol_1_desc": "Build the habit of financial mindfulness every time you spend.",
  "wallet_sol_2_title": "Predictive Control",
  "wallet_sol_2_desc": "You know you're breaking the budget *before* you swipe your card.",
  "wallet_compare_title": "Passive vs Active",
  "wallet_compare_desc": "Who is really in control?",
  "wallet_table_head_2": "Wallet / Mint",
  "wallet_table_row_1_title": "Method",
  "wallet_table_row_1_col_1": "Passive Auto-Sync",
  "wallet_table_row_1_col_2": "Active Mindfulness Logging",
  "wallet_table_row_2_title": "Behavior Change",
  "wallet_table_row_2_col_1": "Minimal",
  "wallet_table_row_2_col_2": "High impact",
  "wallet_table_row_3_title": "Privacy",
  "wallet_table_row_3_col_1": "Sells your banking data",
  "wallet_table_row_3_col_2": "Your data is yours",
  "wallet_science_title": "The Psychology of Friction",
  "wallet_science_desc": "Studies show that people spend 20% less when using cash versus credit cards because it 'hurts' to hand over physical money. Manual logging mimics this psychological friction digitally.",
  "wallet_data_title": "Your Bank Account is Not a Strategy",
  "wallet_data_desc": "Looking at your past transactions is driving while looking in the rearview mirror. You need a system that looks forward.",
  "wallet_cta_title": "Stop being a spectator <br/>to your own wealth.",
  "wallet_cta_desc": "Take the wheel and drive your financial future.",
  "wallet_cta_btn": "Start Manual Tracking",

  // Finance: Spendee
  "explore_spendee_desc": "Beautiful charts mean nothing if they aren't tied to your daily habits and goals.",
  "spendee_alt_title": "OneForMind vs Spendee — The Ultimate Spendee Alternative",
  "spendee_alt_desc": "Spendee is just a pretty calculator. Get a complete Life OS that connects your money to your habits and tasks.",
  "spendee_alt_og_title": "Pretty Charts Don't Pay the Bills.",
  "spendee_alt_og_desc": "Why standalone finance apps like Spendee aren't enough to fix your life.",
  "spendee_badge": "Holistic Wealth System",
  "spendee_hero_title_1": "A Calculator Won't",
  "spendee_hero_title_2": "Fix Your Life.",
  "spendee_hero_desc": "Spendee gives you beautiful pie charts. But charts don't tell you *why* you overspent. <strong>OneForMind connects your finances to your habits</strong>, showing you the root cause of your spending.",
  "spendee_hero_cta": "See The Big Picture",
  "spendee_hero_note": "Finance + Habits + Planner.",
  "spendee_prob_title_1": "The Missing",
  "spendee_prob_title_highlight": "Context",
  "spendee_prob_desc": "If you see a spike in 'Food' spending on Spendee, you don't know why it happened. Was it a bad mood? A missed meal prep habit? Standalone apps are blind to context.",
  "spendee_prob_point_1": "No integration with your daily routines",
  "spendee_prob_point_2": "Just tracks symptoms, not causes",
  "spendee_prob_point_3": "You still need 3 other apps to manage life",
  "spendee_sol_title_1": "Connecting The",
  "spendee_sol_title_highlight": "Dots",
  "spendee_sol_desc": "Because OneForMind is a unified OS, you can see that your $50 takeout spike happened on the same day you missed your 'Grocery Shopping' task in the planner. That's real intelligence.",
  "spendee_sol_1_title": "Root Cause Analysis",
  "spendee_sol_1_desc": "Our AI Coach tells you exactly which habits are draining your wallet.",
  "spendee_sol_2_title": "One Subscription",
  "spendee_sol_2_desc": "Why pay for a finance app, a habit app, and a planner separately?",
  "spendee_compare_title": "Isolated vs Unified",
  "spendee_compare_desc": "Don't settle for half the picture.",
  "spendee_table_head_2": "Spendee",
  "spendee_table_row_1_title": "Context",
  "spendee_table_row_1_col_1": "Blind numbers",
  "spendee_table_row_1_col_2": "Deep behavioral context",
  "spendee_table_row_2_title": "Ecosystem",
  "spendee_table_row_2_col_1": "Finance only",
  "spendee_table_row_2_col_2": "Finance, Planner, Habits, Journal",
  "spendee_table_row_3_title": "Goal Synergy",
  "spendee_table_row_3_col_1": "Basic limits",
  "spendee_table_row_3_col_2": "Tied directly to Life Goals",
  "spendee_ai_title": "The Neural Advantage",
  "spendee_ai_desc": "Our integrated AI doesn't just show you a pie chart. It tells you: 'You spend 30% more on days you don't meditate.' That's the power of a unified system.",
  "spendee_cost_title": "The Fragmentation Tax",
  "spendee_cost_desc": "Paying for Spendee, plus a task manager, plus a habit tracker, is a waste of money and mental energy. Consolidate and conquer.",
  "spendee_cta_title": "Stop tracking symptoms. <br/>Start fixing causes.",
  "spendee_cta_desc": "Upgrade to a system that actually understands you.",
  "spendee_cta_btn": "Unify Your Finances",

  // Planner: Todoist
  "explore_todoist_desc": "Endless laundry lists cause burnout. Upgrade to time-blocking and the Eisenhower Matrix.",
  "todoist_alt_title": "OneForMind vs Todoist — The Ultimate Todoist Alternative",
  "todoist_alt_desc": "Todoist is just an endless laundry list that causes stress. Switch to OneForMind for time-blocking and real prioritization.",
  "todoist_alt_og_title": "Laundry Lists Don't Get Things Done.",
  "todoist_alt_og_desc": "Why Todoist's endless lists cause burnout, and how OneForMind fixes it.",
  "todoist_badge": "Execution Engine",
  "todoist_hero_title_1": "Stop Making Lists.",
  "todoist_hero_title_2": "Start Executing.",
  "todoist_hero_desc": "Todoist lets you pile up 500 tasks with no context. It's a graveyard of good intentions. OneForMind uses <strong>Time-Blocking and the Eisenhower Matrix</strong> to force you to schedule exactly WHEN you'll do the work.",
  "todoist_hero_cta": "Execute Your Day",
  "todoist_hero_note": "Turn tasks into calendar blocks.",
  "todoist_prob_title_1": "The Graveyard of",
  "todoist_prob_title_highlight": "Good Intentions",
  "todoist_prob_desc": "Writing down 'Build website' without scheduling it is just wishing. Todoist's endless lists create a false sense of productivity followed by overwhelming anxiety.",
  "todoist_prob_point_1": "Overwhelming 'Overdue' red text",
  "todoist_prob_point_2": "No built-in calendar scheduling",
  "todoist_prob_point_3": "Treats 'Buy Milk' the same as 'Launch Startup'",
  "todoist_sol_title_1": "Schedule It or",
  "todoist_sol_title_highlight": "Trash It",
  "todoist_sol_desc": "In OneForMind, tasks don't just sit there. You drop them into your daily calendar. If it's not on the calendar, it doesn't exist. We force you to be realistic with your time.",
  "todoist_sol_1_title": "Eisenhower Matrix Built-in",
  "todoist_sol_1_desc": "Instantly separate the Urgent from the Important.",
  "todoist_sol_2_title": "Time-Blocking Native",
  "todoist_sol_2_desc": "Drag tasks directly into your daily timeline.",
  "todoist_compare_title": "Wishing vs Doing",
  "todoist_compare_desc": "How do you handle your day?",
  "todoist_table_head_2": "Todoist",
  "todoist_table_row_1_title": "Philosophy",
  "todoist_table_row_1_col_1": "Collect everything",
  "todoist_table_row_1_col_2": "Schedule what matters",
  "todoist_table_row_2_title": "Prioritization",
  "todoist_table_row_2_col_1": "Basic P1-P4 flags",
  "todoist_table_row_2_col_2": "Visual Eisenhower Matrix",
  "todoist_table_row_3_title": "Habits Integration",
  "todoist_table_row_3_col_1": "Hacky recurring tasks",
  "todoist_table_row_3_col_2": "Dedicated Habit Engine",
  "todoist_psycho_title": "The Zeigarnik Effect",
  "todoist_psycho_desc": "Unfinished tasks cause mental tension. Seeing a list of 50 overdue items on Todoist spikes your cortisol. Scheduling 3 realistic blocks on OneForMind brings peace.",
  "todoist_data_title": "Tasks vs Habits",
  "todoist_data_desc": "Todoist treats habits like regular tasks. But 'Drink Water' is not a task, it's a routine. OneForMind separates them beautifully so your to-do list isn't cluttered.",
  "todoist_cta_title": "Ready to clear the clutter <br/>and get to work?",
  "todoist_cta_desc": "Stop organizing your tasks. Start executing them.",
  "todoist_cta_btn": "Switch to OneForMind",

  // Planner: TickTick
  "explore_ticktick_desc": "Don't just tick boxes. Connect your daily tasks to your long-term life goals.",
  "ticktick_alt_title": "OneForMind vs TickTick — A Smarter TickTick Alternative",
  "ticktick_alt_desc": "TickTick is great for chores, but lacks vision. Switch to a Life OS that connects your daily tasks to your life goals.",
  "ticktick_alt_og_title": "Don't Just Tick Boxes. Build a Life.",
  "ticktick_alt_og_desc": "Why a simple checklist isn't enough to reach your long-term goals.",
  "ticktick_badge": "Vision-Led Planner",
  "ticktick_hero_title_1": "Checking Boxes Isn't",
  "ticktick_hero_title_2": "The Same as Progress.",
  "ticktick_hero_desc": "TickTick is great for remembering to buy groceries. But for building a business or changing your life? You need more. <strong>OneForMind connects your daily tasks directly to your macro life goals.</strong>",
  "ticktick_hero_cta": "Connect Tasks to Goals",
  "ticktick_hero_note": "A planner with a vision.",
  "ticktick_prob_title_1": "The Productivity",
  "ticktick_prob_title_highlight": "Mirage",
  "ticktick_prob_desc": "You can check off 20 tasks in TickTick and still be in the exact same place in life. If your tasks aren't aligned with a larger vision, you're just running on a hamster wheel.",
  "ticktick_prob_point_1": "No high-level goal tracking",
  "ticktick_prob_point_2": "Disconnected from your finances",
  "ticktick_prob_point_3": "Cluttered UI with too many features",
  "ticktick_sol_title_1": "Top-Down",
  "ticktick_sol_title_highlight": "Alignment",
  "ticktick_sol_desc": "In OneForMind, you set a Goal first. Then you create Habits and Tasks that serve that goal. Every time you check a box, you know exactly what mountain you are climbing.",
  "ticktick_sol_1_title": "Macro to Micro",
  "ticktick_sol_1_desc": "See how today's tasks feed your 5-year vision.",
  "ticktick_sol_2_title": "All-in-One Dashboard",
  "ticktick_sol_2_desc": "Tasks, Habits, and Budget all in one clean view.",
  "ticktick_compare_title": "Micro vs Macro",
  "ticktick_compare_desc": "Are you climbing the right mountain?",
  "ticktick_table_head_2": "TickTick",
  "ticktick_table_row_1_title": "Focus",
  "ticktick_table_row_1_col_1": "Getting chores done",
  "ticktick_table_row_1_col_2": "Executing life goals",
  "ticktick_table_row_2_title": "Ecosystem",
  "ticktick_table_row_2_col_1": "Tasks & basic habits",
  "ticktick_table_row_2_col_2": "Tasks, Goals, Finance, Journal",
  "ticktick_table_row_3_title": "Journal Integration",
  "ticktick_table_row_3_col_1": "None",
  "ticktick_table_row_3_col_2": "Deep reflective journaling",
  "ticktick_psycho_title": "The Meaning Crisis",
  "ticktick_psycho_desc": "Task fatigue happens when we lose the 'Why'. By connecting your daily actions to a defined Goal in OneForMind, you restore meaning to your daily grind.",
  "ticktick_data_title": "Design Matters",
  "ticktick_data_desc": "TickTick feels like a utility app. OneForMind feels like a premium sanctuary for your thoughts. A calm environment leads to better focus.",
  "ticktick_cta_title": "Stop running on <br/>a hamster wheel.",
  "ticktick_cta_desc": "Start climbing your mountain with purpose.",
  "ticktick_cta_btn": "Plan With Purpose",

  // Planner: ClickUp
  "explore_clickup_desc": "Stop using enterprise tools for personal life. Get an OS designed for individuals, not corporations.",
  "clickup_alt_title": "OneForMind vs ClickUp — The Best ClickUp Alternative for Individuals",
  "clickup_alt_desc": "ClickUp is bloated corporate software. Switch to OneForMind, the personal OS designed for individual focus, not enterprise micromanagement.",
  "clickup_alt_og_title": "You Are Not a Corporation.",
  "clickup_alt_og_desc": "Why using enterprise tools like ClickUp or Asana ruins your personal productivity.",
  "clickup_badge": "Personal OS",
  "clickup_hero_title_1": "You Are a Human,",
  "clickup_hero_title_2": "Not an Enterprise.",
  "clickup_hero_desc": "ClickUp brags about having 'every feature imaginable'. But you don't need Gantt charts, Jira tickets, or team permissions to run your personal life. <strong>You need clarity, not corporate bloat.</strong>",
  "clickup_hero_cta": "Get Personal Clarity",
  "clickup_hero_note": "Zero corporate jargon.",
  "clickup_prob_title_1": "The Feature",
  "clickup_prob_title_highlight": "Bloat",
  "clickup_prob_desc": "Using ClickUp for personal planning is like using a bulldozer to plant a flower. The endless menus, custom fields, and complex permissions just slow you down.",
  "clickup_prob_point_1": "Painfully slow loading times",
  "clickup_prob_point_2": "Overwhelming enterprise UI",
  "clickup_prob_point_3": "Requires a Ph.D. to set up properly",
  "clickup_sol_title_1": "Opinionated",
  "clickup_sol_title_highlight": "Simplicity",
  "clickup_sol_desc": "OneForMind is an 'Opinionated OS'. We made the hard design choices for you. There are no endless toggles. Just a perfectly crafted system for Habits, Tasks, and Finances that works out of the box.",
  "clickup_sol_1_title": "Lightning Fast",
  "clickup_sol_1_desc": "Instant page loads so you don't lose your train of thought.",
  "clickup_sol_2_title": "Built for Individuals",
  "clickup_sol_2_desc": "We care about your personal growth, not your 'sprint velocity'.",
  "clickup_compare_title": "Corporate vs Personal",
  "clickup_compare_desc": "Use the right tool for the job.",
  "clickup_table_head_2": "ClickUp / Asana",
  "clickup_table_row_1_title": "Target Audience",
  "clickup_table_row_1_col_1": "Large corporate teams",
  "clickup_table_row_1_col_2": "Ambitious individuals",
  "clickup_table_row_2_title": "Setup Time",
  "clickup_table_row_2_col_1": "Days or weeks",
  "clickup_table_row_2_col_2": "Ready in 30 seconds",
  "clickup_table_row_3_title": "Performance",
  "clickup_table_row_3_col_1": "Heavy, slow, complex",
  "clickup_table_row_3_col_2": "Lightweight, instant, calm",
  "clickup_psycho_title": "Decision Fatigue",
  "clickup_psycho_desc": "When an app gives you 50 different ways to view a task, you spend more time organizing than executing. OneForMind removes the friction of choice.",
  "clickup_data_title": "Personal Context",
  "clickup_data_desc": "ClickUp doesn't care about your mood, your habits, or your personal budget. It only cares about deadlines. We care about the whole you.",
  "clickup_cta_title": "Fire your project manager. <br/>Reclaim your peace.",
  "clickup_cta_desc": "Ditch the corporate bloatware and switch to a Personal OS.",
  "clickup_cta_btn": "Switch to a Personal OS"
};

// Data to add for Indonesian
const newId = {
  // Finance: YNAB
  "explore_ynab_desc": "Nggak perlu gelar akuntan cuma buat nyatet kopi. Dapatkan OS Keuangan visual yang nyambung ke habitmu.",
  "ynab_alt_title": "OneForMind vs YNAB — Alternatif YNAB Terbaik",
  "ynab_alt_desc": "YNAB terlalu rumit dan mahal. Beralih ke Finance OS visual yang menghubungkan pengeluaran dengan habit harianmu.",
  "ynab_alt_og_title": "Nggak Butuh Gelar Akuntan Buat Budgeting.",
  "ynab_alt_og_desc": "Kenapa bayar mahal buat aplikasi yang mirip Excel kalau bisa dapet Life OS lengkap?",
  "ynab_badge": "Finance OS Visual",
  "ynab_hero_title_1": "Kamu Butuh Kehidupan,",
  "ynab_hero_title_2": "Bukan Sekadar Budget.",
  "ynab_hero_desc": "YNAB maksain kamu jadi akuntan paruh waktu. OneForMind ngasih <strong>dashboard yang indah dan intuitif</strong>, melacak uang sambil dihubungin ke habit dunia nyatamu. Berhenti pusing sama spreadsheet dan mulailah hidup.",
  "ynab_hero_cta": "Coba Budgeting Visual",
  "ynab_hero_note": "Tanpa perlu gelar akuntansi.",
  "ynab_prob_title_1": "Jebakan",
  "ynab_prob_title_highlight": "Kerumitan",
  "ynab_prob_desc": "Kalau ngatur budget udah kayak ngisi pajak, kamu pasti bakal nyerah. Kurva belajar YNAB yang curam bikin kesadaran finansial jadi beban, bukan habit.",
  "ynab_prob_point_1": "Kurva belajar yang sangat curam",
  "ynab_prob_point_2": "Biaya langganan yang mahal banget",
  "ynab_prob_point_3": "Cuma spreadsheet yang dikasih lipstik",
  "ynab_sol_title_1": "Kejelasan di Atas",
  "ynab_sol_title_highlight": "Kerumitan",
  "ynab_sol_desc": "Kami percaya ngatur uang cukup 2 menit sehari. Tabungan visual, tag transaksi berwarna, dan bar budget simpel ngasih kejelasan instan tanpa pusing.",
  "ynab_sol_1_title": "Keuangan Berbasis Habit",
  "ynab_sol_1_desc": "Lihat persis gimana habit 'Kurangi GoFood' ngaruh ke saldo bankmu.",
  "ynab_sol_2_title": "Brankas Tabungan Visual",
  "ynab_sol_2_desc": "Lihat uangmu tumbuh buat impianmu, bukan sekadar nongkrong di kategori.",
  "ynab_compare_title": "Spreadsheet vs Visual OS",
  "ynab_compare_desc": "Mana yang sebenarnya mau kamu buka tiap hari?",
  "ynab_table_head_2": "YNAB",
  "ynab_table_row_1_title": "Kurva Belajar",
  "ynab_table_row_1_col_1": "Butuh berjam-jam tutorial",
  "ynab_table_row_1_col_2": "Intuitif sejak menit pertama",
  "ynab_table_row_2_title": "Integrasi Habit",
  "ynab_table_row_2_col_1": "Nggak ada",
  "ynab_table_row_2_col_2": "Terintegrasi mendalam",
  "ynab_table_row_3_title": "Harga",
  "ynab_table_row_3_col_1": "$109/tahun",
  "ynab_table_row_3_col_2": "Jauh lebih terjangkau",
  "ynab_cost_title": "Konyolnya Bayar Mahal Buat Hemat Uang",
  "ynab_cost_desc": "Ironis kan: aplikasi yang niatnya bantu hemat uang malah jadi salah satu pengeluaran terbesarmu. Di OneForMind, kamu dapet Life OS lengkap dengan harga lebih murah.",
  "ynab_psycho_title": "Kelelahan Finansial",
  "ynab_psycho_desc": "Saat setiap sen harus 'dikasih tugas', beban mentalnya bikin capek. Kami pakai macro-budget dan petunjuk visual biar kamu tetap sadar tanpa harus burnout.",
  "ynab_cta_title": "Siap mecat robot <br/>akuntanmu?",
  "ynab_cta_desc": "Beralih ke sistem yang masuk akal.",
  "ynab_cta_btn": "Beralih ke OneForMind",

  // Finance: Wallet
  "explore_wallet_desc": "Otomatisasi pasif itu jebakan. Jangan biarkan aplikasi yang kerja sementara dompetmu bocor.",
  "wallet_alt_title": "OneForMind vs Wallet App — Alternatif Wallet Terbaik",
  "wallet_alt_desc": "Sinkronisasi bank pasif di Wallet bikin kamu malas. Ambil kendali aktif atas keuanganmu dengan OneForMind.",
  "wallet_alt_og_title": "Otomatisasi Bikin Kamu Bokek.",
  "wallet_alt_og_desc": "Kenapa aplikasi pencatat pasif kayak Wallet gagal ngubah habit belanjamu.",
  "wallet_badge": "Kesadaran Finansial Aktif",
  "wallet_hero_title_1": "Berhenti Nonton",
  "wallet_hero_title_2": "Uangmu Lenyap.",
  "wallet_hero_desc": "Aplikasi kayak Wallet bangga sama sinkronisasi bank otomatis. Tapi saat aplikasi yang lakuin semuanya, otakmu masuk mode autopilot. <strong>Kamu butuh kesadaran aktif</strong>, bukan laporan otopsi dari rekeningmu yang kosong.",
  "wallet_hero_cta": "Ambil Kendali Aktif",
  "wallet_hero_note": "Rasakan setiap transaksinya.",
  "wallet_prob_title_1": "Ilusi",
  "wallet_prob_title_highlight": "Otomatisasi",
  "wallet_prob_desc": "Sinkron bank kerasa produktif, padahal pasif banget. Kamu cuma buka aplikasi di akhir bulan buat ngeliat kerusakan yang udah terlanjur terjadi.",
  "wallet_prob_point_1": "Kamu nggak 'ngerasain' pengeluaranmu",
  "wallet_prob_point_2": "Telat nyadar kalau udah over-budget",
  "wallet_prob_point_3": "Menciptakan keterlepasan finansial",
  "wallet_sol_title_1": "Gesekan adalah",
  "wallet_sol_title_highlight": "Fitur",
  "wallet_sol_desc": "OneForMind sengaja butuh entri manual. Meluangkan 5 detik buat ngetik kopi Rp50rb maksain kamu mengakui pembelian itu. Gesekan kecil inilah yang beneran ngubah perilaku belanjamu.",
  "wallet_sol_1_title": "Pencatatan Aktif",
  "wallet_sol_1_desc": "Bangun habit kesadaran finansial tiap kali kamu jajan.",
  "wallet_sol_2_title": "Kendali Prediktif",
  "wallet_sol_2_desc": "Kamu tau bakal ngelewatin budget *sebelum* gesek kartu.",
  "wallet_compare_title": "Pasif vs Aktif",
  "wallet_compare_desc": "Siapa yang sebenarnya pegang kendali?",
  "wallet_table_head_2": "Wallet / Mint",
  "wallet_table_row_1_title": "Metode",
  "wallet_table_row_1_col_1": "Auto-Sync Pasif",
  "wallet_table_row_1_col_2": "Pencatatan Kesadaran Aktif",
  "wallet_table_row_2_title": "Perubahan Perilaku",
  "wallet_table_row_2_col_1": "Minimal",
  "wallet_table_row_2_col_2": "Dampak Tinggi",
  "wallet_table_row_3_title": "Privasi",
  "wallet_table_row_3_col_1": "Menjual data perbankanmu",
  "wallet_table_row_3_col_2": "Datamu adalah milikmu",
  "wallet_science_title": "Psikologi Gesekan",
  "wallet_science_desc": "Studi bilang orang belanja 20% lebih dikit pas pakai cash dibanding kartu karena 'sakit' rasanya nyerahin uang fisik. Catat manual niru gesekan psikologis ini secara digital.",
  "wallet_data_title": "Rekening Bank Bukan Strategi",
  "wallet_data_desc": "Ngeliatin transaksi masa lalu itu kayak nyetir sambil ngeliat spion. Kamu butuh sistem yang ngeliat ke depan.",
  "wallet_cta_title": "Berhenti jadi penonton <br/>kekayaanmu sendiri.",
  "wallet_cta_desc": "Ambil alih kemudi dan arahkan masa depan finansialmu.",
  "wallet_cta_btn": "Mulai Catat Manual",

  // Finance: Spendee
  "explore_spendee_desc": "Grafik cantik nggak ada gunanya kalau nggak nyambung sama habit dan tujuan harianmu.",
  "spendee_alt_title": "OneForMind vs Spendee — Alternatif Spendee Utama",
  "spendee_alt_desc": "Spendee cuma kalkulator cantik. Dapatkan Life OS lengkap yang menghubungkan uang dengan habit dan tugasmu.",
  "spendee_alt_og_title": "Grafik Cantik Nggak Bayar Tagihan.",
  "spendee_alt_og_desc": "Kenapa aplikasi keuangan tunggal kayak Spendee nggak cukup buat benerin hidupmu.",
  "spendee_badge": "Sistem Kekayaan Holistik",
  "spendee_hero_title_1": "Kalkulator Nggak Akan",
  "spendee_hero_title_2": "Ngebenerin Hidupmu.",
  "spendee_hero_desc": "Spendee ngasih kamu diagram pie yang cantik. Tapi grafik nggak ngasih tau *kenapa* kamu boros. <strong>OneForMind menghubungkan keuanganmu ke habitmu</strong>, nunjukin akar masalah pengeluaranmu.",
  "spendee_hero_cta": "Lihat Gambaran Besarnya",
  "spendee_hero_note": "Finance + Habits + Planner.",
  "spendee_prob_title_1": "Konteks yang",
  "spendee_prob_title_highlight": "Hilang",
  "spendee_prob_desc": "Kalau kamu liat lonjakan jajan 'Makanan' di Spendee, kamu nggak tau kenapa itu terjadi. Apa karena bad mood? Lupa meal prep? Aplikasi tunggal buta sama konteks.",
  "spendee_prob_point_1": "Nggak ada integrasi sama rutinitas harian",
  "spendee_prob_point_2": "Cuma ngelacak gejala, bukan penyebab",
  "spendee_prob_point_3": "Kamu tetep butuh 3 aplikasi lain buat hidup",
  "spendee_sol_title_1": "Menghubungkan",
  "spendee_sol_title_highlight": "Titik-titik",
  "spendee_sol_desc": "Karena OneForMind itu OS terpadu, kamu bisa liat kalau lonjakan GoFood Rp100rb terjadi di hari yang sama saat kamu ngelewatin tugas 'Belanja Mingguan' di planner. Itu baru kecerdasan nyata.",
  "spendee_sol_1_title": "Analisa Akar Masalah",
  "spendee_sol_1_desc": "AI Coach kami ngasih tau persis habit mana yang nguras dompetmu.",
  "spendee_sol_2_title": "Satu Langganan",
  "spendee_sol_2_desc": "Ngapain bayar aplikasi finance, habit, dan planner secara terpisah?",
  "spendee_compare_title": "Terisolasi vs Terpadu",
  "spendee_compare_desc": "Jangan puas sama setengah gambaran.",
  "spendee_table_head_2": "Spendee",
  "spendee_table_row_1_title": "Konteks",
  "spendee_table_row_1_col_1": "Angka buta",
  "spendee_table_row_1_col_2": "Konteks perilaku mendalam",
  "spendee_table_row_2_title": "Ekosistem",
  "spendee_table_row_2_col_1": "Cuma Keuangan",
  "spendee_table_row_2_col_2": "Keuangan, Planner, Habit, Jurnal",
  "spendee_table_row_3_title": "Sinergi Target",
  "spendee_table_row_3_col_1": "Limit dasar",
  "spendee_table_row_3_col_2": "Terhubung langsung ke Tujuan Hidup",
  "spendee_ai_title": "Keuntungan Neural",
  "spendee_ai_desc": "AI terintegrasi kami nggak cuma ngasih pie chart. Dia ngomong: 'Kamu belanja 30% lebih banyak di hari kamu nggak meditasi.' Itulah kekuatan sistem terpadu.",
  "spendee_cost_title": "Pajak Fragmentasi",
  "spendee_cost_desc": "Bayar buat Spendee, ditambah task manager, ditambah habit tracker, itu buang-buang uang dan energi mental. Satukan dan taklukkan.",
  "spendee_cta_title": "Berhenti melacak gejala. <br/>Mulai perbaiki penyebab.",
  "spendee_cta_desc": "Upgrade ke sistem yang beneran ngertiin kamu.",
  "spendee_cta_btn": "Satukan Keuanganmu",

  // Planner: Todoist
  "explore_todoist_desc": "Daftar cucian tanpa akhir cuma bikin burnout. Upgrade ke time-blocking dan Matriks Eisenhower.",
  "todoist_alt_title": "OneForMind vs Todoist — Alternatif Todoist Terbaik",
  "todoist_alt_desc": "Todoist cuma daftar cucian tanpa akhir yang bikin stres. Beralih ke OneForMind untuk time-blocking dan penentuan prioritas nyata.",
  "todoist_alt_og_title": "Daftar Panjang Nggak Nyelesein Kerjaan.",
  "todoist_alt_og_desc": "Kenapa daftar tanpa akhir di Todoist bikin burnout, dan gimana OneForMind memperbaikinya.",
  "todoist_badge": "Mesin Eksekusi",
  "todoist_hero_title_1": "Berhenti Bikin List.",
  "todoist_hero_title_2": "Mulai Mengeksekusi.",
  "todoist_hero_desc": "Todoist ngebiarin kamu numpuk 500 tugas tanpa konteks. Itu kuburan niat baik. OneForMind pakai <strong>Time-Blocking dan Matriks Eisenhower</strong> buat maksa kamu ngejadwalin KAPAN pastinya kamu bakal kerja.",
  "todoist_hero_cta": "Eksekusi Harimu",
  "todoist_hero_note": "Ubah tugas jadi blok kalender.",
  "todoist_prob_title_1": "Kuburan",
  "todoist_prob_title_highlight": "Niat Baik",
  "todoist_prob_desc": "Nulis 'Bikin website' tanpa ngejadwalinnya itu cuma harapan kosong. Daftar tanpa akhir Todoist ngasih ilusi produktivitas yang ujung-ujungnya bikin cemas parah.",
  "todoist_prob_point_1": "Teks merah 'Overdue' yang mengintimidasi",
  "todoist_prob_point_2": "Nggak ada penjadwalan kalender bawaan",
  "todoist_prob_point_3": "Nyamain tugas 'Beli Susu' sama 'Bikin Startup'",
  "todoist_sol_title_1": "Jadwalkan atau",
  "todoist_sol_title_highlight": "Buang Saja",
  "todoist_sol_desc": "Di OneForMind, tugas nggak cuma diem doang. Kamu masukin ke kalender harianmu. Kalau nggak ada di kalender, itu nggak eksis. Kami maksa kamu buat realistis sama waktumu.",
  "todoist_sol_1_title": "Matriks Eisenhower Bawaan",
  "todoist_sol_1_desc": "Pisahkan yang Mendesak dari yang Penting secara instan.",
  "todoist_sol_2_title": "Time-Blocking Native",
  "todoist_sol_2_desc": "Tarik tugas langsung ke timeline harianmu.",
  "todoist_compare_title": "Berharap vs Bertindak",
  "todoist_compare_desc": "Gimana kamu ngadepin harimu?",
  "todoist_table_head_2": "Todoist",
  "todoist_table_row_1_title": "Filosofi",
  "todoist_table_row_1_col_1": "Kumpulin semuanya",
  "todoist_table_row_1_col_2": "Jadwalkan yang penting",
  "todoist_table_row_2_title": "Prioritas",
  "todoist_table_row_2_col_1": "Bendera P1-P4 dasar",
  "todoist_table_row_2_col_2": "Matriks Eisenhower Visual",
  "todoist_table_row_3_title": "Integrasi Habit",
  "todoist_table_row_3_col_1": "Tugas berulang yang maksa",
  "todoist_table_row_3_col_2": "Mesin Habit Khusus",
  "todoist_psycho_title": "Efek Zeigarnik",
  "todoist_psycho_desc": "Tugas yang belum selesai bikin tegang mental. Ngeliat 50 tugas telat di Todoist naikin kortisolmu. Ngejadwalin 3 blok realistis di OneForMind bawa kedamaian.",
  "todoist_data_title": "Tugas vs Habit",
  "todoist_data_desc": "Todoist nganggap habit kayak tugas biasa. Padahal 'Minum Air' itu bukan tugas, itu rutinitas. OneForMind misahin keduanya dengan cantik biar to-do list kamu nggak berantakan.",
  "todoist_cta_title": "Siap bersihin kekacauan <br/>dan mulai kerja?",
  "todoist_cta_desc": "Berhenti ngatur tugasmu. Mulai eksekusi mereka.",
  "todoist_cta_btn": "Beralih ke OneForMind",

  // Planner: TickTick
  "explore_ticktick_desc": "Jangan cuma nyentang kotak. Hubungkan tugas harian ke tujuan hidup jangka panjangmu.",
  "ticktick_alt_title": "OneForMind vs TickTick — Alternatif TickTick yang Lebih Pintar",
  "ticktick_alt_desc": "TickTick bagus buat bersih-bersih, tapi kurang visi. Beralih ke Life OS yang menghubungkan tugas harian ke tujuan hidupmu.",
  "ticktick_alt_og_title": "Jangan Cuma Nyentang Kotak. Bangun Hidupmu.",
  "ticktick_alt_og_desc": "Kenapa checklist biasa nggak cukup buat nyapai tujuan jangka panjangmu.",
  "ticktick_badge": "Planner Berbasis Visi",
  "ticktick_hero_title_1": "Nyentang Kotak Itu",
  "ticktick_hero_title_2": "Bukan Berarti Progres.",
  "ticktick_hero_desc": "TickTick bagus buat ngingetin beli belanjaan. Tapi buat bangun bisnis atau ngubah hidup? Kamu butuh lebih. <strong>OneForMind menghubungkan tugas harianmu langsung ke tujuan hidup makromu.</strong>",
  "ticktick_hero_cta": "Hubungkan Tugas ke Tujuan",
  "ticktick_hero_note": "Planner yang punya visi.",
  "ticktick_prob_title_1": "Fatamorgana",
  "ticktick_prob_title_highlight": "Produktivitas",
  "ticktick_prob_desc": "Kamu bisa nyentang 20 tugas di TickTick dan tetep ada di posisi hidup yang sama. Kalau tugasmu nggak sejalan sama visi besar, kamu cuma lari di roda hamster.",
  "ticktick_prob_point_1": "Nggak ada pelacakan target tingkat tinggi",
  "ticktick_prob_point_2": "Terputus dari keuanganmu",
  "ticktick_prob_point_3": "UI berantakan kebanyakan fitur",
  "ticktick_sol_title_1": "Penyelarasan",
  "ticktick_sol_title_highlight": "Top-Down",
  "ticktick_sol_desc": "Di OneForMind, kamu bikin Target dulu. Baru kamu bikin Habit dan Tugas yang ngelayanin target itu. Tiap kali kamu nyentang kotak, kamu tau persis gunung apa yang lagi didaki.",
  "ticktick_sol_1_title": "Makro ke Mikro",
  "ticktick_sol_1_desc": "Lihat gimana tugas hari ini ngasih makan visi 5 tahunmu.",
  "ticktick_sol_2_title": "Dashboard All-in-One",
  "ticktick_sol_2_desc": "Tugas, Habit, dan Anggaran semua dalam satu tampilan bersih.",
  "ticktick_compare_title": "Mikro vs Makro",
  "ticktick_compare_desc": "Apa kamu mendaki gunung yang bener?",
  "ticktick_table_head_2": "TickTick",
  "ticktick_table_row_1_title": "Fokus",
  "ticktick_table_row_1_col_1": "Nyelesein kerjaan rumah",
  "ticktick_table_row_1_col_2": "Mengeksekusi tujuan hidup",
  "ticktick_table_row_2_title": "Ekosistem",
  "ticktick_table_row_2_col_1": "Tugas & habit dasar",
  "ticktick_table_row_2_col_2": "Tugas, Target, Keuangan, Jurnal",
  "ticktick_table_row_3_title": "Integrasi Jurnal",
  "ticktick_table_row_3_col_1": "Nggak ada",
  "ticktick_table_row_3_col_2": "Jurnal reflektif mendalam",
  "ticktick_psycho_title": "Krisis Makna",
  "ticktick_psycho_desc": "Kelelahan tugas terjadi saat kita kehilangan 'Kenapa'-nya. Dengan menghubungkan tindakan harian ke Target yang jelas di OneForMind, kamu mengembalikan makna ke rutinitas harianmu.",
  "ticktick_data_title": "Desain Itu Penting",
  "ticktick_data_desc": "TickTick kerasa kayak aplikasi utilitas. OneForMind kerasa kayak ruang suci premium buat pikiranmu. Lingkungan yang tenang ngasilin fokus yang lebih baik.",
  "ticktick_cta_title": "Berhenti lari di <br/>roda hamster.",
  "ticktick_cta_desc": "Mulai daki gunungmu dengan tujuan yang jelas.",
  "ticktick_cta_btn": "Rencanakan dengan Tujuan",

  // Planner: ClickUp
  "explore_clickup_desc": "Berhenti pakai alat perusahaan buat kehidupan pribadi. Pakai OS yang dirancang buat individu, bukan korporasi.",
  "clickup_alt_title": "OneForMind vs ClickUp — Alternatif ClickUp Terbaik untuk Individu",
  "clickup_alt_desc": "ClickUp itu software perusahaan yang lebay. Beralih ke OneForMind, OS pribadi yang didesain buat fokus individu, bukan micromanagement perusahaan.",
  "clickup_alt_og_title": "Kamu Itu Bukan Korporasi.",
  "clickup_alt_og_desc": "Kenapa pakai alat perusahaan kayak ClickUp atau Asana merusak produktivitas pribadimu.",
  "clickup_badge": "Personal OS",
  "clickup_hero_title_1": "Kamu Itu Manusia,",
  "clickup_hero_title_2": "Bukan Perusahaan.",
  "clickup_hero_desc": "ClickUp pamer punya 'semua fitur yang bisa dibayangin'. Tapi kamu nggak butuh Gantt chart, tiket Jira, atau izin tim buat jalanin hidup pribadimu. <strong>Kamu butuh kejelasan, bukan keribetan korporat.</strong>",
  "clickup_hero_cta": "Dapatkan Kejelasan",
  "clickup_hero_note": "Nggak ada bahasa korporat.",
  "clickup_prob_title_1": "Kebanyakan",
  "clickup_prob_title_highlight": "Fitur",
  "clickup_prob_desc": "Pakai ClickUp buat planner pribadi itu kayak pakai buldoser buat nanam bunga. Menu tanpa akhir, custom field, dan izin kompleks cuma bikin kamu lambat.",
  "clickup_prob_point_1": "Waktu loading yang super lambat",
  "clickup_prob_point_2": "UI perusahaan yang bikin pusing",
  "clickup_prob_point_3": "Butuh gelar Ph.D buat setup doang",
  "clickup_sol_title_1": "Kesederhanaan yang",
  "clickup_sol_title_highlight": "Berprinsip",
  "clickup_sol_desc": "OneForMind itu 'Opinionated OS'. Kami udah ngambil keputusan desain yang susah buat kamu. Nggak ada toggle tanpa akhir. Cuma sistem sempurna buat Habit, Tugas, dan Keuangan yang langsung siap pakai.",
  "clickup_sol_1_title": "Secepat Kilat",
  "clickup_sol_1_desc": "Loading halaman instan biar kamu nggak lupa apa yang mau dipikirin.",
  "clickup_sol_2_title": "Dibuat buat Individu",
  "clickup_sol_2_desc": "Kami peduli sama pertumbuhan pribadimu, bukan 'sprint velocity'-mu.",
  "clickup_compare_title": "Korporat vs Personal",
  "clickup_compare_desc": "Pakai alat yang tepat buat kerjaannya.",
  "clickup_table_head_2": "ClickUp / Asana",
  "clickup_table_row_1_title": "Target Audiens",
  "clickup_table_row_1_col_1": "Tim perusahaan besar",
  "clickup_table_row_1_col_2": "Individu yang ambisius",
  "clickup_table_row_2_title": "Waktu Setup",
  "clickup_table_row_2_col_1": "Berhari-hari atau berminggu-minggu",
  "clickup_table_row_2_col_2": "Siap dalam 30 detik",
  "clickup_table_row_3_title": "Performa",
  "clickup_table_row_3_col_1": "Berat, lambat, rumit",
  "clickup_table_row_3_col_2": "Ringan, instan, tenang",
  "clickup_psycho_title": "Kelelahan Keputusan",
  "clickup_psycho_desc": "Saat aplikasi ngasih 50 cara beda buat liat tugas, kamu ngabisin lebih banyak waktu buat ngatur daripada ngerjain. OneForMind ngilangin beban milih-milih.",
  "clickup_data_title": "Konteks Personal",
  "clickup_data_desc": "ClickUp nggak peduli sama moodmu, habitmu, atau budget pribadimu. Dia cuma peduli deadline. Kami peduli soal kamu seutuhnya.",
  "clickup_cta_title": "Pecat manajer proyekmu. <br/>Rebut kembali ketenanganmu.",
  "clickup_cta_desc": "Tinggalkan software korporat yang lebay dan beralih ke Personal OS.",
  "clickup_cta_btn": "Beralih ke Personal OS"
};

Object.assign(enData, newEn);
Object.assign(idData, newId);

fs.writeFileSync(enFile, JSON.stringify(enData, null, 2), 'utf8');
fs.writeFileSync(idFile, JSON.stringify(idData, null, 2), 'utf8');
console.log('Language files updated successfully.');
