<?php

$root = 'c:/Users/Axioo/dopmymind';
$partials = [
    'en' => $root . '/lang/partials/en/',
    'id' => $root . '/lang/partials/id/'
];

$solutionsData = [
    'en' => [
        "solve_finance_hero_badge" => "Wealth System",
        "solve_finance_hero_title_1" => "Total Control Over Your",
        "solve_finance_hero_title_2" => "Financial Future.",
        "solve_finance_hero_desc" => "Say goodbye to financial anxiety. Track income, monitor expenses, and align your spending with your life goals in one beautiful dashboard.",
        "solve_finance_hero_cta" => "Master Your Money",
        "finance_mockup_assets" => "Personal Assets",
        "finance_mockup_growth" => "Wealth Velocity",
        "finance_mockup_income" => "Total Income",
        "finance_mockup_expenses" => "Total Expenses",
        "finance_mockup_goal" => "Financia Goal Progress",
        "finance_science_viz_title" => "THE WEALTH ENGINE",
        "finance_science_viz_sub" => "Neural Synergy Intelligence",
        "solve_finance_prob_title" => "The Financial Anxiety Trap",
        "solve_finance_prob_desc" => "Managing money shouldn't feel like a punishment. Most systems fail because they lack connection to your habits.",
        "solve_finance_prob_1_title" => "Subtle Leaks",
        "solve_finance_prob_1_point_1" => "Unconscious Spending",
        "solve_finance_prob_1_point_2" => "Subscription Fatigue",
        "solve_finance_prob_1_point_3" => "Cash Flow Friction",
        "solve_finance_prob_2_title" => "No Emergency Buffer",
        "solve_finance_prob_2_point_1" => "Living Check-to-Check",
        "solve_finance_prob_2_point_2" => "Stagnant Savings",
        "solve_finance_prob_2_point_3" => "Month-End Anxiety",
        "finance_science_viz_status_badge" => "SYSTEM STATUS",
        "finance_science_viz_status_title" => "Optimized Wealth",
        "solve_finance_sol_feat_1_title" => "Financial Clarity",
        "solve_finance_sol_feat_1_desc" => "Track every cent with ease.",
        "solve_finance_sol_feat_2_title" => "Smart Budgeting",
        "solve_finance_sol_feat_2_desc" => "Automated limits and alerts.",
        "solve_finance_sol_feat_3_title" => "Wealth Roadmap",
        "solve_finance_sol_feat_3_desc" => "Project your future net worth.",
        "solve_finance_syn_title" => "The Synergy Loop",
        "solve_finance_syn_desc" => "Connect habits to cash flow.",
        "finance_synergy_habit_title" => "Coffee Habit",
        "finance_synergy_habit_desc" => "Saved $5 on coffee.",
        "finance_synergy_alloc_title" => "Saved to Wealth",
        "finance_synergy_alloc_amount" => "+$5.00",
        "solve_finance_extra_1_title" => "Cash Flow Visualization",
        "solve_finance_extra_1_desc" => "Understand your financial ebbs and flows with easy-to-read charts. Identify seasonal trends and adjust your lifestyle before cash flow turns negative.",
        "solve_finance_extra_2_title" => "Smart Savings Targets",
        "solve_finance_extra_2_desc" => "Want to buy a house or go on vacation? Set specific goals and let OneForMind calculate how much to set aside each month to achieve them on time.",
        "finance_extra_1_label" => "Balance Flow",
        "finance_extra_2_label" => "MONTHS TO FREEDOM",
        "solve_finance_science_badge" => "WEALTH ARCHITECTURE",
        "solve_finance_science_title" => "Conscious Allocation Methodology",
        "solve_finance_science_desc" => "We use 'Pay Yourself First' and 'Zero-Based Budgeting' principles. Our system ensures every dollar has a job, reducing impulse buys and increasing savings.",
        "finance_science_principle_1_title" => "Mindful Saving",
        "finance_science_principle_2_title" => "Resource Allocation",
        "finance_science_principle_3_title" => "The Compounding Effect",
        "solve_finance_faq_title" => "Finance Mastery FAQ",
        "solve_finance_faq_q1" => "Do I need to connect my bank?",
        "solve_finance_faq_a1" => "For maximum privacy and security, OneForMind currently focuses on fast manual input or CSV uploads, ensuring there is no direct access to your bank accounts.",
        "solve_finance_faq_q2" => "Can I track multiple currencies?",
        "solve_finance_faq_a2" => "Yes, our system supports multi-currency to help you manage global assets in one place.",
        "solve_finance_faq_q3" => "Is my financial data truly secure?",
        "solve_finance_faq_a3" => "Your data is fully encrypted. We use the same security standards as modern banking apps to protect your sensitive financial information.",
        "solve_finance_cta_title" => "Ready for Financial Freedom?",
        "solve_finance_cta_desc" => "Start building your wealth foundation now with the most intuitive system.",
        "solve_finance_cta_btn" => "Start Managing My Money",

        // COMMON / LAYOUT
        "Security" => "Security",
        "Logo" => "Logo",
        "OneForMind" => "OneForMind",
        "Pricing" => "Pricing",
        "Dashboard" => "Dashboard",
        "Features" => "Features",
        "Solutions" => "Solutions",
        "Resources" => "Resources",
        "Connect" => "Connect",
        "Product" => "Product",
        "Compare" => "Compare",
        "Company" => "Company",
        "Privacy Policy" => "Privacy Policy",
        "Terms of Service" => "Terms of Service",
        "Refund Policy" => "Refund Policy",
        "Contact Us" => "Contact Us",
        "About Us" => "About Us",
        "System Status" => "System Status"
    ],
    'id' => [
        "solve_finance_hero_badge" => "Sistem Kekayaan",
        "solve_finance_hero_title_1" => "Kendali Penuh Atas",
        "solve_finance_hero_title_2" => "Masa Depat Finansial Anda.",
        "solve_finance_hero_desc" => "Ucapkan selamat tinggal pada kecemasan finansial. Lacak pendapatan, pantau pengeluaran, dan selaraskan pemakaian uang dengan tujuan hidup Anda.",
        "solve_finance_hero_cta" => "Kuasai Uang Anda",
        "finance_mockup_assets" => "Aset Pribadi",
        "finance_mockup_growth" => "Kecepatan Kekayaan",
        "finance_mockup_income" => "Total Pendapatan",
        "finance_mockup_expenses" => "Total Pengeluaran",
        "finance_mockup_goal" => "Progres Target",
        "finance_science_viz_title" => "MESIN KEKAYAAN",
        "finance_science_viz_sub" => "Kecerdasan Sinergi Neural",
        "solve_finance_prob_title" => "Jebakan Kecemasan Finansial",
        "solve_finance_prob_desc" => "Mengelola uang tidak seharusnya terasa seperti hukuman. Kebanyakan sistem gagal karena tidak terhubung dengan kebiasaan.",
        "solve_finance_prob_1_title" => "Kebocoran Halus",
        "solve_finance_prob_1_point_1" => "Pengeluaran Tak Disadari",
        "solve_finance_prob_1_point_2" => "Kelelahan Biaya Langganan",
        "solve_finance_prob_1_point_3" => "Hambatan Arus Kas",
        "solve_finance_prob_2_title" => "Tanpa Dana Darurat",
        "solve_finance_prob_2_point_1" => "Hidup Pas-pasan",
        "solve_finance_prob_2_point_2" => "Tabungan Stagnan",
        "solve_finance_prob_2_point_3" => "Kecemasan Akhir Bulan",
        "finance_science_viz_status_badge" => "STATUS SISTEM",
        "finance_science_viz_status_title" => "Kekayaan Optimal",
        "solve_finance_sol_feat_1_title" => "Kejelasan Finansial",
        "solve_finance_sol_feat_1_desc" => "Lacak setiap perak dengan mudah.",
        "solve_finance_sol_feat_2_title" => "Budgeting Pintar",
        "solve_finance_sol_feat_2_desc" => "Batas dan peringatan otomatis.",
        "solve_finance_sol_feat_3_title" => "Peta Jalan Kekayaan",
        "solve_finance_sol_feat_3_desc" => "Proyeksikan kekayaan bersih masa depan Anda.",
        "solve_finance_syn_title" => "Loop Sinergi",
        "solve_finance_syn_desc" => "Hubungkan kebiasaan ke arus kas.",
        "finance_synergy_habit_title" => "Kebiasaan Kopi",
        "finance_synergy_habit_desc" => "Hemat Rp 75rb hari ini.",
        "finance_synergy_alloc_title" => "Disimpan ke Aset",
        "finance_synergy_alloc_amount" => "+Rp 75.000",
        "solve_finance_extra_1_title" => "Visualisasi Arus Kas",
        "solve_finance_extra_1_desc" => "Pahami pasang surut finansial Anda dengan grafik yang mudah dibaca. Identifikasi tren sebelum menjadi masalah.",
        "solve_finance_extra_2_title" => "Target Menabung Cerdas",
        "solve_finance_extra_2_desc" => "Ingin membeli rumah atau berlibur? Tetapkan tujuan dan biarkan OneForMind menghitung berapa yang harus disisihkan.",
        "finance_extra_1_label" => "Aliran Saldo",
        "finance_extra_2_label" => "BULAN MENUJU BEBAS",
        "solve_finance_science_badge" => "ARSITEKTUR KEKAYAAN",
        "solve_finance_science_title" => "Metodologi Alokasi Sadar",
        "solve_finance_science_desc" => "Kami menggunakan prinsip 'Bayar Diri Sendiri Dulu' dan 'Zero-Based Budgeting'. Sistem memasikan setiap rupiah punya tugas.",
        "finance_science_principle_1_title" => "Menabung Sadar",
        "finance_science_principle_2_title" => "Alokasi Sumber Daya",
        "finance_science_principle_3_title" => "Efek Compounding",
        "solve_finance_faq_title" => "FAQ Keuangan",
        "solve_finance_faq_q1" => "Perlu hubungkan bank?",
        "solve_finance_faq_a1" => "Untuk privasi maksimal, OneForMind saat ini fokus pada entri manual yang cepat atau unggah CSV.",
        "solve_finance_faq_q2" => "Mata uang ganda?",
        "solve_finance_faq_a2" => "Ya, sistem kami mendukung banyak mata uang di satu tempat.",
        "solve_finance_faq_q3" => "Apakah data aman?",
        "solve_finance_faq_a3" => "Data Anda sepenuhnya terenkripsi dengan standar keamanan perbankan modern.",
        "solve_finance_cta_title" => "Siap untuk Kebebasan?",
        "solve_finance_cta_desc" => "Mulai bangun fondasi kekayaan Anda hari ini.",
        "solve_finance_cta_btn" => "Mulai Kelola Uang Saya",

        // COMMON / LAYOUT (ID)
        "Security" => "Keamanan",
        "Logo" => "Logo",
        "OneForMind" => "OneForMind",
        "Pricing" => "Harga",
        "Dashboard" => "Dashboard",
        "Features" => "Fitur",
        "Solutions" => "Solusi",
        "Resources" => "Sumber Daya",
        "Connect" => "Hubungkan",
        "Product" => "Produk",
        "Compare" => "Bandingkan",
        "Company" => "Perusahaan",
        "Privacy Policy" => "Kebijakan Privasi",
        "Terms of Service" => "Syarat Layanan",
        "Refund Policy" => "Kebijakan Refund",
        "Contact Us" => "Hubungi Kami",
        "About Us" => "Tentang Kami",
        "System Status" => "Status Sistem"
    ]
];

foreach (['en', 'id'] as $lang) {
    $filePath = $partials[$lang] . '/missing_auto.json';
    $data = file_exists($filePath) ? json_decode(file_get_contents($filePath), true) : [];

    foreach ($solutionsData[$lang] as $key => $val) {
        $data[$key] = $val;
    }

    ksort($data);
    file_put_contents($filePath, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
}
