[providers]
php = true
node = true

[phases.setup]
nixPkgs = ['php83', 'php83Packages.intl', 'php83Packages.zip', 'nodejs_20', 'npm']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']